import { NodeStatsType } from "./Stats";

export type Node = {
  id: string;
  type: string;
  base?: boolean;
  tier?: "small" | "medium" | "large";
  angle?: number;
  distance?: number;
};

export type NodeTypeMetadata = {
  name: string;
  description: string[];
  hasAsset?: boolean;
  unselectedAsset?: string;
  selectableAsset?: string;
  selectedAsset?: string;
  color: string;
  cost: number;
  stats?: NodeStatsType;
};

export type SkillNodesType = {
  types: { [key: string]: NodeTypeMetadata };
  nodes: { [key: string]: Node };
  edges: { [key: string]: string[] };
};

// ANGLE LINES
export const LinesAngles = [
  15, 45, 75, 105, 135, 165, 195, 225, 255, 285, 315, 345,
];

const SHROUD_TIME_TEXT =
  "<b>Shroud Time</b><br/>Nếu thời gian này hết, màn sương sẽ thiêu rụi bạn.";
const BLOCK_BREAKER =
  "<b>Block Breaker</b><br/>Đòn tấn công đặc biệt này làm tăng thanh choáng của kẻ địch gấp đôi khi bị trúng đòn..";
const OVERPOWER =
  "<b>Overpower</b><br/>Để làm choáng 1 kẻ địch, hãy lấp đầy thanh choáng của chúng bằng cách tấn công khi chúng đỡ đòn hoặc phản đòn tấn công của chúng.";

const SkillNodes: SkillNodesType = {
  types: {
    GIANT_SLAYER_HOOK: {
      name: "GIANT SLAYER HOOK",
      description: [
        "Sử dụng Grappling Hook để kéo bản thân về phía kẻ địch to.",
      ],
      hasAsset: true,
      selectableAsset: "giant_slayer_hook_1.png",
      selectedAsset: "giant_slayer_hook_2.png",
      color: "gold",
      cost: 5,
    },
    GROUNDING_HOOK: {
      name: "GROUNDING HOOK",
      description: [
        "Sử dụng Grappling Hook để kéo bản thân về phía kẻ địch bay.",
      ],
      hasAsset: true,
      color: "gold",
      cost: 2,
    },
    SAVIOUR: {
      name: "SAVIOUR",
      description: [
        "Bạn chỉ cần 3s thay vì 6s để <b>cứu đồng đội</b>.",
      ],
      color: "gold",
      cost: 2,
    },
    BACKSTAB_DAMAGE: {
      name: "BACKSTAB DAMAGE",
      description: ["Tăng 25% sát thương khi tấn công từ phía sau."],
      color: "gold",
      cost: 2,
    },
    OPPORTUNITY: {
      name: "OPPORTUNITY",
      description: [
        "Tăng hệ số tấn công Thô Bạo và Lén Lún lên 100%.",
      ],
      color: "gold",
      cost: 3,
    },
    MINER: {
      name: "MINER",
      description: [
        "Khi bạn khai thác tài nguyên, có 10% cơ hội nhận thêm 1 tài nguyên đó.",
      ],
      color: "gold",
      cost: 4,
    },
    LUMBERJACK: {
      name: "LUMBERJACK",
      description: [
        "Rìu chặt gây thêm 30% tổn hại lên các vật bằng gỗ.",
      ],
      color: "gold",
      cost: 2,
    },
    QUALITY_GEAR: {
      name: "QUALITY GEAR",
      description: ["Tất cả công cụ giảm 50% tiêu hao độ bền."],
      color: "gold",
      cost: 2,
    },
    MASON: {
      name: "MASON",
      description: [
        "Cuốc chim gây thêm 30% tổn hại lên các vật bằng đá, bao gồm cả quặng .",
      ],
      color: "gold",
      cost: 2,
    },
    POWER_PARRY: {
      name: "POWER PARRY",
      description: [
        "Tăng thời gian bị choáng của địch khi phản đòn thành công.",
        "<b>Parry</b><br>Khi trang bị khiên, ấn <b>[RMB] để đỡ</b>. Đỡ đòn đúng lúc sẽ <b>phản đòn</b> tấn công của địch.",
      ],
      color: "gold",
      cost: 2,
    },
    ATTR_SPIRIT: {
      name: "SPIRIT",
      description: [
        "Tăng thuộc tính Tinh Thần của bạn thêm 1",
        "Tăng thêm 20 năng lượng cho mỗi Điểm thuộc tính",
      ],
      color: "blue",
      cost: 1,
      stats: { SPIRIT: 1 },
    },
    ATTR_INT: {
      name: "INTELLIGENCE",
      description: [
        "Tăng thuộc tính Trí Tuệ của bạn thêm 1",
        "Tăng thêm 5% sát thương phép thuật cho mỗi Điểm thuộc tính",
      ],
      color: "blue",
      cost: 1,
      stats: { INT: 1 },
    },
    ATTR_CONS: {
      name: "CONSTITUTION",
      description: [
        "Tăng thuộc tính Sinh Lực của bạn thêm 1",
        "Tăng thêm 50 Máu cho mỗi Điểm thuộc tính",
      ],
      color: "red",
      cost: 1,
      stats: { CONS: 1 },
    },
    ATTR_STR: {
      name: "STRENGTH",
      description: [
        "Tăng thuộc tính Sức Mạnh của bạn thêm 1",
        "Tăng thêm 5% sát thương cận chiến cho mỗi Điểm thuộc tính",
      ],
      color: "red",
      cost: 1,
      stats: { STR: 1 },
    },
    ATTR_ENDURANCE: {
      name: "ENDURANCE",
      description: [
        "Tăng thuộc tính Sức Bền của bạn thêm 1",
        "Tăng thêm 10 thể lực cho mỗi Điểm thuộc tính",
      ],
      color: "green",
      cost: 1,
      stats: { ENDURANCE: 1 },
    },
    ATTR_DEX: {
      name: "DEXTERITY",
      description: [
        "Tăng thuộc tính Khéo Léo của bạn thêm 1",
        "Tăng thêm 5% sát thương tầm xa cho mỗi Điểm thuộc tính",
      ],
      color: "green",
      cost: 1,
      stats: { DEX: 1 },
    },
    WELL_RESTED: {
      name: "WELL RESTED",
      description: [
        "Thời gian cơ bản cho hiệu ứng Nghỉ ngơi được tăng thêm 5 phút.",
        "Tăng mức độ Thoải mái trong nhà của bạn để tăng thêm thời gian hiệu quả.",
      ],
      color: "gold",
      cost: 1,
    },
    SNEAK_ATTACK: {
      name: "SNEAK ATTACK",
      description: [
        "<b>Tấn công lén lút</b> gây ra lượng sát thương lớn gấp 10 lần lên kẻ địch không hề hay biết.",
        "Để kích hoạt, hãy lẻn đến gần kẻ địch và nhấn <b>[E]</b>.",
      ],
      hasAsset: true,
      selectableAsset: "sneak_attack_1.png",
      selectedAsset: "sneak_attack_2.png",
      color: "gold",
      cost: 3,
    },
    MERCILESS_ATTACK: {
      name: "MERCILESS ATTACK",
      description: [
        "Thực hiện 1 đòn Tấn công thô bạo bằng cách nhấn [E] để gây sát thương lớn lên kẻ địch.",
        OVERPOWER,
      ],
      hasAsset: true,
      selectableAsset: "merciless_attack_1.png",
      selectedAsset: "merciless_attack_2.png",
      color: "gold",
      cost: 2,
    },
    UPDRAFT: {
      name: "UPDRAFT",
      description: [
        "Nhấn nút nhảy trong khi lướt sẽ giúp bạn tăng độ cao một chút. Kỹ năng này có thể sử dụng một lần cho mỗi lượt bay. Tiêu hao: 120 năng lượng",
      ],
      hasAsset: true,
      color: "green",
      cost: 4,
    },
    BEGONE: {
      name: "BEGONE",
      description: [
        "Một cú đấm có sức mạnh ma thuật đẩy và làm choáng kẻ địch trúng đòn.",
        "Thay thế các đòn tấn công không vũ khí của bạn miễn là bạn có đủ năng lượng cần thiết: <b>30 năng lượng</b>",
      ],
      hasAsset: true,
      color: "blue",
      cost: 3,
    },
    RADIANT_AURA: {
      name: "RADIANT AURA",
      description: [
        "Tất cả kẻ địch xung quanh trong bán kính 10 mét nhận 1 sát thương lửa với mỗi điểm trí tuệ theo từng giây.",
      ],
      hasAsset: true,
      color: "blue",
      cost: 3,
    },
    WATER_AURA: {
      name: "WATER AURA",
      description: [
        "Bạn phát ra hào quang chữa lành. Nó chữa lành tất cả đồng minh bị thương trong phạm vi 15 mét. Hiệu ứng chữa lành tỷ lệ thuận với thuộc tính Trí Tuệ của bạn (1 máu cho mỗi 2 điểm Trí Tuệ).",
      ],
      hasAsset: true,
      color: "blue",
      cost: 3,
    },
    MARTYR: {
      name: "MARTYR",
      description: [
        "Khi bạn bị kẻ địch hạ gục, tất cả đồng minh trong phạm vi 50 mét sẽ được hồi 30% máu tối đa.",
      ],
      hasAsset: true,
      color: "blue",
      cost: 5,
    },
    BLINK: {
      name: "BLINK",
      description: [
        "Thay thế khả năng Né tránh bằng khả năng dịch chuyển tức thời tầm ngắn.",
      ],
      hasAsset: true,
      color: "blue",
      cost: 4,
    },
    EVASION_ATTACK: {
      name: "EVASION ATTACK",
      description: [
        "Khi trang bị vũ khí cận chiến, bạn có thể thực hiện đòn tấn công lao về phía kẻ địch và gây thêm sát thương bằng cách nhấn <b>[LMB]</b>",
        BLOCK_BREAKER,
      ],
      hasAsset: true,
      color: "red",
      cost: 4,
    },
    EARTH_AURA: {
      name: "EARTH AURA",
      description: [
        "Bảo vệ đồng minh và bản thân, giảm 10% sát thương nhận vào",
      ],
      hasAsset: true,
      color: "red",
      cost: 5,
    },
    NEMESIS: {
      name: "NEMESIS",
      description: [
        "Bạn thu hút kẻ địch khi 1 đồng minh khác bị chú ý.",
      ],
      hasAsset: true,
      color: "red",
      cost: 5,
    },
    SHOCKWAVE: {
      name: "SHOCKWAVE",
      description: [
        "Kích hoạt sóng xung kích khi bạn đỡ đòn tấn công hoặc chế ngự kẻ địch.",
        "Sóng xung kích đẩy lùi kẻ địch ở gần. Nó cũng tăng thời gian choáng của chúng theo thuộc tính Sức Mạnh của bạn.",
        OVERPOWER,
      ],
      hasAsset: true,
      color: "red",
      cost: 3,
    },
    HEAVY_SPECIALIZATION: {
      name: "HEAVY SPECIALIZATION",
      description: ["Cho phép bạn tấn công nhanh hơn với búa cầm hai tay."],
      hasAsset: true,
      color: "red",
      cost: 5,
    },
    BASH: {
      name: "BASH",
      description: [
        "Phản đòn gây 20 sát thương. Sát thương được tăng lên theo thuộc tính Sức Mạnh của bạn",
      ],
      hasAsset: true,
      color: "red",
      cost: 5,
    },
    JUMP_ATTACK: {
      name: "JUMP ATTACK",
      description: [
        "Khi trang bị vũ khí cận chiến, nhảy lên tấn công gây thêm 50% sát thương trong phạm vi nhỏ",
        "Đòn tấn công nhảy tốn thể lực theo trọng lượng của vũ khí. Không có tác dụng với công cụ",
        BLOCK_BREAKER,
      ],
      hasAsset: true,
      color: "red",
      cost: 3,
    },
    DOUBLE_JUMP: {
      name: "DOUBLE JUMP",
      description: ["Cho phép bạn nhảy 2 lần."],
      hasAsset: true,
      color: "green",
      cost: 4,
    },
    DESSERT_STOMACH: {
      name: "DESSERT STOMACH",
      description: ["Bạn nhận thêm 1 ô chứa thức ăn"],
      hasAsset: true,
      color: "green",
      cost: 4,
    },
    EAGLE_EYE: {
      name: "EAGLE EYE",
      description: [
        "Tăng đáng kể khả năng phóng to khi ngắm bằng cung.",
        "Để ngắm, giữ phím [RMB]. (Hoặc giữ phím [Q] để ngắm cung đã trang bị của bạn.)",
      ],
      hasAsset: true,
      color: "green",
      cost: 3,
    },
    MULTI_SHOT: {
      name: "MULTI SHOT",
      description: [
        "Khi sử dụng mũi tên thường, có 20% khả năng tạo ra một loạt mũi tên trong phạm vi nhỏ.",
        "Điều này sẽ tốn thêm mũi tên, nhưng sẽ không kích hoạt trên mũi tên đặc biệt.",
      ],
      hasAsset: true,
      color: "green",
      cost: 3,
    },
    MULTI_SHOT_SPREAD: {
      name: "MULTI SHOT SPREAD",
      description: [
        `Thêm 25% cơ hội tạo ra 1 mũi tên bổ sung vào "loạt tên" của bạn từ kỹ năng "Multi Shot".`,
        "Mũi tên bổ sung không tiêu hao số mũi tên của bạn",
      ],
      color: "green",
      cost: 4,
    },
    MULTI_SHOT_TRIGGER: {
      name: "MULTI SHOT TRIGGER",
      description: [
        `TẤT CẢ các mũi tên, bao gồm cả mũi tên đặc biệt, đều có thể kích hoạt "MULTI SHOT".`,
        "Multi Shot sẽ trừ vào số mũi tên của bạn.",
      ],
      color: "green",
      cost: 3,
    },
    BEE_STING: {
      name: "BEE STING",
      description: [
        "Bạn kéo cung khi đang ở trên không sẽ khiến bạn rơi chậm lại trong một thời gian ngắn. Mỗi cú bắn sẽ tạo lực đẩy để bạn có thêm thời gian ở trên không.",
        "Tiêu hao: 10 thể lực mỗi giây",
      ],
      hasAsset: true,
      color: "green",
      cost: 3,
    },
    SHELL_SHOCK: {
      name: "SHELL SHOCK",
      description: [
        "Truyền năng lượng vào <i>chất nổ tầm xa</i>. Chúng giờ đây có thể làm choáng kẻ địch trong 1 giây.",
        "Tiêu hao: 5 năng lượng cho mỗi kẻ địch bị choáng",
      ],
      hasAsset: true,
      color: "green",
      cost: 5,
    },
    COUNTERSTRIKE: {
      name: "COUNTERSTRIKE",
      description: [
        "Sau khi nhận sát thương, có 20% cơ hội phản lại 50% sát thương cho kẻ tấn công dưới dạng thiêu đốt.",
        "Đòn tấn công ma thuật này có thể kích hoạt các kỹ năng khác.",
      ],
      color: "blue",
      cost: 2,
    },
    TERROR: {
      name: "TERROR",
      description: [
        "Khi đòn phép thuật chí mạng, mục tiêu sẽ bị choáng trong 4 giây.",
      ],
      color: "blue",
      cost: 4,
    },
    QUICK_CHARGE: {
      name: "QUICK CHARGE",
      description: [
        "Giảm 50% thời gian cần thiết để Gậy tích tụ 1 phép thuật",
      ],
      color: "blue",
      cost: 3,
    },
    THIS_IS_THE_WAY: {
      name: "THIS IS THE WAY",
      description: [
        "Khi tấn công bằng vũ khí phép thuật, tăng thêm 10% sát thương",
      ],
      color: "blue",
      cost: 2,
    },
    ARSONIST: {
      name: "ARSONIST",
      description: ["Tăng thêm 10% sát thương thiêu đốt."],
      color: "blue",
      cost: 2,
    },
    PYROMANIAC: {
      name: "PYROMANIAC",
      description: ["Tăng thêm 20% sát thương thiêu đốt."],
      color: "blue",
      cost: 3,
    },
    SUN_AURA: {
      name: "SUN AURA",
      description: [
        "Tất cả kẻ địch trong phạm vi 10 mét phải chịu thêm 1 sát thương thiêu đốt với mỗi điểm Trí Tuệ theo từng giây",
      ],
      color: "blue",
      cost: 2,
    },
    THUNDER: {
      name: "THUNDER",
      description: ["Tăng thêm 10% sát thương giật điện."],
      color: "blue",
      cost: 2,
    },
    LIGHTNING: {
      name: "LIGHTNING",
      description: ["Tăng thêm 20% sát thương giật điện."],
      color: "blue",
      cost: 3,
    },
    ICEMAN: {
      name: "ICEMAN",
      description: ["Tăng thêm 10% sát thương băng."],
      color: "blue",
      cost: 2,
    },
    SUBZERO: {
      name: "SUBZERO",
      description: ["Tăng thêm 20% sát thương băng."],
      color: "blue",
      cost: 3,
    },
    FROST: {
      name: "FROST",
      description: [
        "Khi nhận sát thương cận chiến, kẻ tấn công sẽ bị làm chậm trong 3 giây.",
      ],
      color: "blue",
      cost: 3,
    },
    WIZARD: {
      name: "WIZARD",
      description: [
        "Khi tấn công bằng vũ khí phép thuật, cơ hội chí mạng của bạn tăng thêm 10%.",
      ],
      color: "blue",
      cost: 3,
    },
    DARK_ARTS: {
      name: "DARK ARTS",
      description: ["Tăng thêm 10% sát thương màn sương."],
      color: "blue",
      cost: 3,
    },
    ABYSS: {
      name: "ABYSS",
      description: ["Tăng thêm 20% sát thương màn sương."],
      color: "blue",
      cost: 4,
    },
    CHAIN_HIT: {
      name: "CHAIN HIT",
      description: [
        "Khi gây chí mạng bằng vũ khí ma thuật, sẽ tự động tấn công thêm kẻ địch thứ hai trong phạm vi 15 mét, gây 5 sát thương giật điện cho mỗi chỉ số Trí Tuệ.",
      ],
      color: "blue",
      cost: 3,
    },
    MASS_DESTRUCTION: {
      name: "MASS DESTRUCTION",
      description: [
        "Khi gây chí mạng bằng vũ khí ma thuật, sẽ tự động tấn công tất cả kẻ địch trong phạm vi 20 mét, gây 2 sát thương giật điện cho mỗi chỉ số Trí Tuệ.",
      ],
      color: "blue",
      cost: 4,
    },
    NECROMANCER: {
      name: "NECROMANCER",
      description: [
        "Khi giết kẻ địch bằng vũ khí ma thuật, có 10% cơ hội triệu hồi 1 quái vật xương.",
      ],
      color: "blue",
      cost: 3,
    },
    HEALER: {
      name: "HEALER",
      description: [
        "Lượng máu nhận được từ phép thuật chữa lành sẽ tăng thêm 10%.",
      ],
      color: "blue",
      cost: 2,
    },
    HEALER_II: {
      name: "HEALER II",
      description: ["Lượng máu nhận được từ phép thuật chữa lành sẽ tăng thêm 20%"],
      color: "blue",
      cost: 2,
    },
    HEALING_REVIVE: {
      name: "HEALING REVIVE",
      description: [
        "Người chơi được cứu sẽ hồi phục 25% lượng máu thay vì 10%.",
      ],
      color: "blue",
      cost: 2,
    },
    SHROUD_FILTER: {
      name: "SHROUD FILTER",
      description: [
        "Gây sát thương bằng vũ khí phép thuật có 15% cơ hội kích hoạt một vụ nổ nhỏ giúp phục hồi 30 giây <i>thời gian ảnh hưởng của màn sương</i> cho bạn và đồng minh trong phạm vi 20 mét.",
        SHROUD_TIME_TEXT,
      ],
      color: "blue",
      cost: 3,
    },
    WATERS_OF_LIFE: {
      name: "WATERS OF LIFE",
      description: [
        "Tăng khả năng hồi phục của <b>Water Aura</b> lên 2 máu cho mỗi 2 chỉ số Trí Tuệ.",
      ],
      color: "blue",
      cost: 2,
    },
    EMERGENCY_BLINK: {
      name: "EMERGENCY BLINK",
      description: [
        "Bạn có thể dịch chuyển khi bị choáng. Thao tác này sẽ giải trạng thái bị choáng.",
      ],
      color: "blue",
      cost: 2,
    },
    BLINK_ATTACK: {
      name: "BLINK ATTACK",
      description: [
        "Dịch chuyển tới kẻ địch sẽ kích hoạt một vụ nổ gây sát thương lửa trong phạm vi nhỏ.",
        "Sát thương và tiêu hao năng lượng tỷ lệ với chỉ số Trí Tuệ",
      ],
      color: "blue",
      cost: 2,
    },
    ARCANE_DEFLECTION: {
      name: "ARCANE DEFLECTION",
      description: ["Phản đòn thành công, hồi lại 20 Năng lượng."],
      color: "blue",
      cost: 3,
    },
    UNITY: {
      name: "UNITY",
      description: [
        "Gây sát thương cho kẻ địch bằng đũa phép có 24% cơ hội hồi phục 4% Năng lượng.",
      ],
      color: "blue",
      cost: 3,
    },
    WAND_MASTER: {
      name: "WAND MASTER",
      description: [
        "Tấn công bằng đũa phép có 30% cơ hội phóng ra thêm 1 đạn phép gây 50% sát thương.",
      ],
      color: "blue",
      cost: 3,
    },
    ETERNAL_SPARK: {
      name: "ETERNAL SPARK",
      description: [
        "Đạn phép có 25% cơ hội không tiêu hao độ bền.",
      ],
      color: "blue",
      cost: 3,
    },
    STING: {
      name: "STING",
      description: ["Sát thương của đũa phép tăng 20% khi sử dụng liên tục."],
      color: "blue",
      cost: 3,
    },
    BATTLE_HEAL: {
      name: "BATTLE HEAL",
      description: [
        "Khi gây sát thương chí mạng bằng vũ khí cận chiến, hồi phục 5% lượng máu tối đa.",
      ],
      color: "red",
      cost: 3,
    },
    BLOODLETTING: {
      name: "BLOODLETTING",
      description: [
        "Khi tung đòn chí mạng bằng vũ khí phép thuật, có 50% cơ hội tạo ra 2 quả cầu máu, năng lượng hoặc thể lực.",
        "Thu thập quả cầu sẽ bổ sung 10% tài nguyên tương ứng.",
      ],
      color: "blue",
      cost: 3,
    },
    LIFE_BURST: {
      name: "LIFE BURST",
      description: [
        "Khi tiêu diệt kẻ địch bằng vũ khí phép thuật, tất cả người chơi trong phạm vi 15 mét tính từ mục tiêu sẽ nhận được lượng máu bằng 3 lần chỉ số Trí Tuệ của bạn.",
      ],
      color: "blue",
      cost: 4,
    },
    BLOOD_MAGIC: {
      name: "BLOOD MAGIC",
      description: [
        "Khi Năng lượng của bạn giảm xuống dưới 20%, bạn sẽ phục hồi lại 35% lượng Năng lượng tối đa của mình với chi phí là 1 máu cho mỗi Năng lượng. Quá trình này sẽ dừng lại ở 1 máu",
        "<b>Thời gian hồi chiêu</b><br />Quá trình này mất 2 phút trước khi có thể kích hoạt lại.",
      ],
      color: "blue",
      cost: 4,
    },
    ABSORB: {
      name: "ABSORB",
      description: [
        "Khi bạn chịu sát thương phép thuật, bạn có 10% cơ hội tạo ra 1 Năng lượng cho mỗi điểm máu bị mất.",
      ],
      color: "red",
      cost: 3,
    },
    SNAP: {
      name: "SNAP",
      description: ["Phục hồi 10% Năng lượng khi kích hoạt đòn tấn công thô bạo."],
      color: "red",
      cost: 4,
    },
    SOUL_LEECH: {
      name: "SOUL LEECH",
      description: [
        "Khi tiêu diệt kẻ địch bằng vũ khí cận chiến, tất cả người chơi trong phạm vi 15 mét tính từ mục tiêu sẽ nhận được 20 Năng lượng.",
      ],
      color: "red",
      cost: 4,
    },
    SHINY_PLATES: {
      name: "SHINY PLATES",
      description: ["Tăng 10% chỉ số giáp vật lý"],
      color: "red",
      cost: 2,
    },
    HEAVY_PLATES: {
      name: "HEAVY PLATES",
      description: [
        "Lượng sát thương vật lý tối đa mà áo giáp của bạn có thể chịu đựng được tăng thêm 10%",
      ],
      color: "red",
      cost: 2,
    },
    WARDEN: {
      name: "WARDEN",
      description: [
        "Khi có 3 kẻ địch trở lên trong phạm vi 20 mét, giảm 15% sát thương phép thuật nhận phải.",
      ],
      color: "red",
      cost: 3,
    },
    TOWER: {
      name: "TOWER",
      description: [
        "Khi có 3 kẻ địch trở lên trong phạm vi 20 mét, giảm 10% sát thương vật lý nhận phải.",
      ],
      color: "red",
      cost: 3,
    },
    ARCH_NEMESIS: {
      name: "ARCH NEMESIS",
      description: [
        "Bạn sẽ tăng mạnh khả năng thu hút kẻ địch khi đồng minh bị chú ý",
      ],
      color: "red",
      cost: 3,
    },
    PURIFICATION: {
      name: "PURIFICATION",
      description: [
        "Sau khi đánh bại kẻ địch bị màn sương xâm chiếm bằng vũ khí cận chiến, bạn sẽ được hồi lại 5 giây Thời gian bị màn sương ảnh hưởng.",
        SHROUD_TIME_TEXT,
      ],
      color: "red",
      cost: 3,
    },
    WARRIOR_PATH: {
      name: "THE WARRIOR'S PATH",
      description: [
        "Khi tấn công bằng vũ khí cận chiến, toàn bộ sát thương sẽ tăng thêm 10%.",
      ],
      color: "red",
      cost: 2,
    },
    THRUST: {
      name: "THRUST",
      description: [
        "Tăng 10% sát thương đâm",
      ],
      color: "red",
      cost: 2,
    },
    PIERCE: {
      name: "PIERCE",
      description: [
        "Tăng 20% sát thương đâm.",
      ],
      color: "red",
      cost: 3,
    },
    BRUTE: {
      name: "BRUTE",
      description: [
        "Tăng 10% sát thương đập.",
      ],
      color: "red",
      cost: 2,
    },
    HAMMER_TIME: {
      name: "HAMMER TIME",
      description: [
        "Tăng 20% sát thương đập.",
      ],
      color: "red",
      cost: 3,
    },
    SLASHER: {
      name: "SLASHER",
      description: [
        "Tăng 10% sát thương chém.",
      ],
      color: "red",
      cost: 2,
    },
    BUTCHER: {
      name: "BUTCHER",
      description: [
        "Tăng 20% sát thương chém.",
      ],
      color: "red",
      cost: 3,
    },
    VETERAN: {
      name: "VETERAN",
      description: [
        "Khi tấn công bằng vũ khí cận chiến, tăng thêm 10% cơ hội chí mạng.",
      ],
      color: "red",
      cost: 4,
    },
    SWIFT_BLADES: {
      name: "SWIFT BLADES",
      description: [
        "Cho phép bạn tấn công nhanh hơn bằng kiếm và rìu một tay.",
      ],
      color: "red",
      cost: 5,
    },
    FEAST: {
      name: "FEAST",
      description: ["Thịt tăng thêm 15% máu."],
      color: "red",
      cost: 3,
    },
    HEAVY_HANDED: {
      name: "HEAVY HANDED",
      description: [
        "Tăng thêm 20% thời gian choáng khi tấn công bằng vũ khí cận chiến vào kẻ địch đang đỡ đòn.",
      ],
      color: "red",
      cost: 2,
    },
    STEADFAST: {
      name: "STEADFAST",
      description: [
        "Đánh bại kẻ địch bằng vũ khí cận chiến sẽ phục hồi 1 độ bền cho vũ khí đó.",
      ],
      color: "red",
      cost: 3,
    },
    BREACH: {
      name: "BREACH",
      description: [
        "Kẻ địch quá mạnh sẽ phải chịu thêm 100% sát thương cận chiến trong 3 giây.",
        OVERPOWER,
      ],
      color: "red",
      cost: 3,
    },
    RELENTLESS: {
      name: "RELENTLESS",
      description: [
        "Gây sát thương chí mạng bằng vũ khí cầm hai tay sẽ tăng thêm 10% cơ hội chí mạng cho đòn đánh tiếp theo.",
      ],
      color: "red",
      cost: 5,
    },
    BARBARIAN: {
      name: "BARBARIAN",
      description: [
        "Bạn sẽ tăng 1 cấp độ Sức Mạnh với mỗi 2 cấp độ của Ngọn lửa.",
      ],
      color: "red",
      cost: 5,
    },
    BLOOD_RAGE: {
      name: "BLOOD RAGE",
      description: [
        "Khi tiêu diệt kẻ địch trong phạm vi 10 mét bằng vũ khí cận chiến, sát thương gây ra bằng vũ khí cận chiến sẽ tăng 20% ​​trong 10 giây.",
      ],
      color: "red",
      cost: 5,
    },
    VIGOROUS_DEFLECTION: {
      name: "VIGOROUS DEFLECTION",
      description: ["Bạn nhận được 30 thể lực khi phản đòn thành công."],
      color: "red",
      cost: 2,
    },
    BLOOD_WARRIOR: {
      name: "BLOOD WARRIOR",
      description: [
        "Tạo ra một quả cầu Máu sau khi đánh bại kẻ địch bằng đòn tấn công lén lút hoặc tấn công thô bạo.",
        "Thu thập các quả cầu sẽ hồi phục 10% máu của bạn.",
      ],
      color: "red",
      cost: 3,
    },
    FINESSE: {
      name: "FINESSE",
      description: [
        "Vũ khí cận chiến một tay và dao găm có 20% cơ hội không bị mất độ bền.",
      ],
      color: "red",
      cost: 3,
    },
    JUMP_ATTACK_II: {
      name: "JUMP ATTACK II",
      description: [
        "Khi trang bị vũ khí cận chiến, tấn công bằng cú nhảy kép sẽ gây thêm 20% sát thương.",
      ],
      color: "green",
      cost: 3,
    },
    BACKSTAB_MASTERY: {
      name: "BACKSTAB MASTERY",
      description: ["Tăng 30% sát thương gây ra từ phía sau."],
      color: "green",
      cost: 4,
    },
    RUNNER: {
      name: "RUNNER",
      description: [
        "Tốc độ chạy tăng 10% và tiêu hao thể lực giảm 10%",
      ],
      color: "green",
      cost: 2,
    },
    WANDERLUST: {
      name: "WANDERLUST",
      description: [
        "Tiêu hao thể lực khi <b>chạy trên đường đất</b> giảm từ <b>90% xuống 80%</b>. Tiêu hao thể lực <b>chạy trên đường đá</b> giảm từ <b>75% xuống 50%</b>.",
      ],
      color: "green",
      cost: 3,
    },
    GOOD_METABOLISM: {
      name: "GOOD METABOLISM",
      description: [
        "Quả cầu máu, năng lượng và thể lực phục hồi 30% thay vì 10%.",
        "Bình năng lượng và máu phục hồi tăng thêm 20%.",
      ],
      color: "green",
      cost: 3,
    },
    SWIFTSHOT_SUSTENANCE: {
      name: "SWIFTSHOT SUSTENANCE",
      description: [
        "30% cơ hội tạo ra quả cầu thể lực khi đánh bại kẻ địch bằng cung.",
      ],
      color: "green",
      cost: 2,
    },
    SWEET_TOOTH: {
      name: "SWEET TOOTH",
      description: ["Khả năng phục hồi thể lực của đồ ngọt tăng 50%"],
      color: "green",
      cost: 3,
    },
    ARACHNOID: {
      name: "ARACHNOID",
      description: ["Tiêu hao thể lực khi leo trèo giảm 50%"],
      color: "green",
      cost: 3,
    },
    REBOUND: {
      name: "REBOUND",
      description: ["Tăng khả năng phục hồi thể lực cơ bản lên 50%"],
      color: "green",
      cost: 4,
    },
    INNER_FIRES: {
      name: "INNER FIRES",
      description: [
        "<i>Thời gian ảnh hưởng từ màn sương</i> tăng thêm 2 phút, cho phép bạn khám phá lâu hơn.",
        SHROUD_TIME_TEXT,
      ],
      color: "green",
      cost: 2,
    },
    RELENTLESS_FLAME: {
      name: "RELENTLESS FLAME",
      description: [
        "<i>Thời gian ảnh hưởng từ màn sương</i> tăng thêm 5 phút, cho phép bạn khám phá lâu hơn.",
        SHROUD_TIME_TEXT,
      ],
      color: "green",
      cost: 4,
    },
    SNAKE_EATER: {
      name: "SNAKE EATER",
      description: [
        "Tăng <b>kháng độc</b>, giúp giảm <b>20%</b> sát thương độc.",
      ],
      color: "green",
      cost: 2,
    },
    MITHRIDATIST: {
      name: "MITHRIDATIST",
      description: [
        "<b>Khả năng kháng độc</b> tăng thêm 10%.",
        "Bạn cũng có thêm 25% cơ hội tránh bị nhiễm độc.",
      ],
      color: "green",
      cost: 3,
    },
    DAGGER_MASTER: {
      name: "DAGGER MASTER",
      description: ["Tăng 15% sát thương của dao găm."],
      color: "green",
      cost: 4,
    },
    SLICE_AND_DICE: {
      name: "SLICE AND DICE",
      description: [
        "Sau khi gây chí mạng bằng dao găm, đòn tấn công tiếp theo bằng cung sẽ tăng 50% sát thương.",
      ],
      color: "green",
      cost: 3,
    },
    VUKAH_LANGUAGE: {
      name: "VUKAH LANGUAGE",
      description: [
        "Vukah trong phạm vi 50 mét sẽ không tấn công bạn trừ khi bị khiêu khích.",
      ],
      color: "green",
      cost: 3,
    },
    CALM_SPIRIT: {
      name: "CALM SPIRIT",
      description: [
        "<b>Động vật hoang dã</b> trong phạm vi 50 mét sẽ được xoa dịu trừ khi bị tấn công. Không ảnh hưởng đến động vật bị xâm chiếm bởi màn sương.",
      ],
      color: "green",
      cost: 3,
    },
    BEAST_MASTER: {
      name: "BEAST MASTER",
      description: [
        "Khi bạn bị tấn công, <b>động vật hoang dã</b> trong phạm vi 50 mét sẽ tấn công kẻ địch.",
      ],
      color: "green",
      cost: 4,
    },
    VUKAH_CULTURE: {
      name: "VUKAH CULTURE",
      description: [
        "Khi bạn bị nhắm tới, Vukah trong phạm vi 50 mét sẽ tấn công kẻ địch.",
      ],
      color: "green",
      cost: 4,
    },
    ENDURANCE_OF_THE_FLAME: {
      name: "ENDURANCE OF THE FLAME",
      description: [
        "Bạn sẽ nhận được 1 điểm Sức Bền với mỗi 2 cấp độ của Ngọn lửa.",
      ],
      color: "green",
      cost: 5,
    },
    MARKSMAN: {
      name: "MARKSMAN",
      description: ["Tất cả sát thương tầm xa được tăng thêm 20%"],
      color: "green",
      cost: 2,
    },
    SHARPSHOOTER: {
      name: "SHARPSHOOTER",
      description: ["Tất cả sát thương tầm xa được tăng thêm 20%"],
      color: "green",
      cost: 2,
    },
    COUNTER_BATTERY: {
      name: "COUNTER BATTERY",
      description: ["Tăng 15% sát thương lên kẻ địch đánh xa."],
      color: "green",
      cost: 2,
    },
    EAGLES_BANE: {
      name: "EAGLES BANE",
      description: ["Tăng 30% sát thương đối vẻ kẻ địch bay."],
      color: "green",
      cost: 3,
    },
    SKILL_SHOT: {
      name: "SKILL SHOT",
      description: ["Tăng 20% sát thương."],
      color: "green",
      cost: 3,
    },
    RANGER: {
      name: "RANGER",
      description: [
        "+2 Sức Bền<br>+2 Khéo Léo<br>+5 Phục hồi thể lực<br>+5% Tỉ lệ chí mạng<br>+5% Sát thương chí mạng",
      ],
      color: "green",
      cost: 4,
      stats: {
        DEX: 2,
        ENDURANCE: 2,
      },
    },
    SILENT_STRIDE: {
      name: "SILENT STRIDE",
      description: ["Tăng tốc độ di chuyển của bạn khi lén lút."],
      color: "green",
      cost: 3,
    },
    AIRBORNE: {
      name: "AIRBORNE",
      description: ["Giảm 30% thể lực khi lướt."],
      color: "green",
      cost: 2,
    },
    SNIPER: {
      name: "SNIPER",
      description: [
        "Khi tấn công bằng vũ khí tầm xa, tăng thêm 10% cơ hội chí mạng.",
      ],
      color: "green",
      cost: 2,
    },
    VITALITY_SURGE: {
      name: "VITALITY SURGE",
      description: [
        "Khi gây đòn chí mạng bằng vũ khí tầm xa sẽ hồi lại 5 điểm thể lực.",
      ],
      color: "green",
      cost: 3,
    },
    BLESSED_ARROWS: {
      name: "BLESSED ARROWS",
      description: [
        "Khi gây đòn chí mạng bằng cung, bạn sẽ hồi lại 20 năng lượng.",
      ],
      color: "green",
      cost: 3,
    },
    BOUNTY_BONANZA: {
      name: "BOUNTY BONANZA",
      description: [
        "Sau khi đánh bại kẻ địch bằng một phát bắn vào đầu, nhóm của bạn sẽ nhận thêm 5 Điểm kinh nghiệm.",
      ],
      color: "green",
      cost: 3,
    },
    RICOCHETS: {
      name: "RICOCHETS",
      description: [
        "Với mỗi mục tiêu bạn bắn trúng bằng Mũi tên nổ, sát thương của nó sẽ tăng thêm 1%..",
      ],
      color: "green",
      cost: 4,
    },
    GRACEFUL_STRIDE: {
      name: "GRACEFUL STRIDE",
      description: [
        "Bạn sẽ nhận được 1 điểm Khéo Léo với mỗi 2 cấp độ của Ngọn lửa.",
      ],
      color: "green",
      cost: 5,
    },
    CHAIN_REACTION: {
      name: "CHAIN REACTION",
      description: [
        "Mỗi kẻ địch bị trúng Mũi tên nổ có 20% khả năng kích hoạt một vụ nổ thứ 2 gây 50% sát thương trong phạm vi nhỏ.",
      ],
      color: "green",
      cost: 5,
    },
    ARCANE_CONCENTRATION: {
      name: "ARCANE CONCENTRATION",
      description: [
        "Bạn sẽ nhận được 1 điểm Tinh Thần với mỗi 2 cấp độ của Ngọn lửa.",
      ],
      color: "blue",
      cost: 5,
    },
    EXALTED: {
      name: "EXALTED",
      description: [
        "Bạn sẽ nhận được 1 điểm Trí Tuệ với mỗi 2 cấp độ của Ngọn lửa.",
      ],
      color: "blue",
      cost: 5,
    },
    THICK_SKIN: {
      name: "THICK SKIN",
      description: [
        "Bạn sẽ nhận được 1 điểm Sinh Lực với mỗi 2 cấp độ của Ngọn lửa.",
      ],
      color: "red",
      cost: 5,
    },
    LIFE_ESSENCES: {
      name: "LIFE ESSENCES",
      description: [
        "Máu tối đa của bạn được tăng gấp 5 lần tùy theo chỉ số Trí Tuệ của bạn.",
      ],
      color: "blue",
      hasAsset: true,
      cost: 5,
    },
    POISONED_BLADES: {
      name: "POISONED BLADES",
      description: [
        "Tăng cơ hội đầu độc kẻ địch lên 25% khi sử dụng dao găm có đặc tính độc.",
      ],
      color: "green",
      cost: 3,
    },
    POISON_MASTERY: {
      name: "POISON MASTERY",
      description: [
        "Dao găm tăng 100% sát thương gây ra khi kích hoạt Poisoned Blades.",
      ],
      color: "green",
      cost: 4,
    },
    QUICK_REFLEX_BLOCK: {
      name: "QUICK REFLEX BLOCK",
      description: [
        "Tăng hiệu quả đỡ đòn của bạn trong thời gian ngắn khi chặn bằng dao găm đôi, giảm thể lực tiêu hao khi phản đòn thành công.",
      ],
      color: "green",
      cost: 4,
    },
  },
  nodes: {
    "1": {
      id: "1",
      type: "WELL_RESTED",
      base: true,
      tier: "medium",
      distance: -120,
      angle: 255,
    },
    "2": {
      id: "2",
      type: "SNEAK_ATTACK",
      base: true,
      tier: "large",
      distance: -120,
      angle: 225,
    },
    "3": {
      id: "3",
      type: "BACKSTAB_DAMAGE",
      tier: "medium",
      distance: -190,
      angle: 225,
    },
    "181": {
      id: "181",
      type: "OPPORTUNITY",
      tier: "medium",
      distance: -250,
      angle: 225,
    },
    "4": {
      id: "4",
      type: "LUMBERJACK",
      base: true,
      tier: "medium",
      distance: -120,
      angle: 165,
    },
    "5": {
      id: "5",
      type: "QUALITY_GEAR",
      tier: "medium",
      distance: -120,
      angle: 120,
    },
    "6": { id: "6", type: "MINER", tier: "medium", distance: -190, angle: 120 },
    "7": {
      id: "7",
      type: "MASON",
      base: true,
      tier: "medium",
      distance: -120,
      angle: 75,
    },
    "8": {
      id: "8",
      type: "MERCILESS_ATTACK",
      base: true,
      tier: "large",
      distance: -120,
      angle: 15,
    },
    "9": {
      id: "9",
      type: "POWER_PARRY",
      tier: "medium",
      distance: -190,
      angle: 15,
    },
    "10": {
      id: "10",
      type: "SAVIOUR",
      base: true,
      tier: "medium",
      distance: -120,
      angle: 315,
    },
    "11": {
      id: "11",
      type: "ATTR_SPIRIT",
      base: true,
      tier: "small",
      angle: 255,
    },
    "12": {
      id: "12",
      type: "COUNTERSTRIKE",
      tier: "medium",
      distance: 70,
      angle: 255,
    },
    "13": {
      id: "13",
      type: "ATTR_INT",
      tier: "small",
      distance: 170,
      angle: 250,
    },
    "14": {
      id: "14",
      type: "ATTR_SPIRIT",
      tier: "small",
      distance: 170,
      angle: 260,
    },
    "15": {
      id: "15",
      type: "BEGONE",
      tier: "large",
      distance: 240,
      angle: 255,
    },
    "17": {
      id: "17",
      type: "ATTR_SPIRIT",
      tier: "small",
      distance: 310,
      angle: 250,
    },
    "16": {
      id: "16",
      type: "ATTR_INT",
      tier: "small",
      distance: 310,
      angle: 260,
    },
    "68": {
      id: "68",
      type: "BLOOD_MAGIC",
      tier: "medium",
      distance: 380,
      angle: 250,
    },
    "64": {
      id: "64",
      type: "BLOODLETTING",
      tier: "medium",
      distance: 380,
      angle: 255,
    },
    "18": {
      id: "18",
      type: "TERROR",
      tier: "medium",
      distance: 380,
      angle: 260,
    },
    "19": {
      id: "19",
      type: "ARCANE_CONCENTRATION",
      tier: "small",
      distance: 450,
      angle: 255,
    },
    "20": {
      id: "20",
      type: "QUICK_CHARGE",
      tier: "medium",
      distance: 120,
      angle: 270,
    },
    "21": { id: "21", type: "ATTR_SPIRIT", base: true, angle: 285 },
    "22": {
      id: "22",
      type: "THIS_IS_THE_WAY",
      tier: "medium",
      distance: 70,
      angle: 285,
    },
    "23": {
      id: "23",
      type: "NECROMANCER",
      tier: "medium",
      distance: 120,
      angle: 300,
    },
    "24": { id: "24", type: "ATTR_SPIRIT", distance: 140, angle: 285 },
    "25": {
      id: "25",
      type: "ARSONIST",
      tier: "medium",
      distance: 210,
      angle: 277,
    },
    "26": {
      id: "26",
      type: "THUNDER",
      tier: "medium",
      distance: 210,
      angle: 285,
    },
    "27": {
      id: "27",
      type: "ICEMAN",
      tier: "medium",
      distance: 210,
      angle: 293,
    },
    "28": {
      id: "28",
      type: "PYROMANIAC",
      tier: "medium",
      distance: 280,
      angle: 277,
    },
    "29": {
      id: "29",
      type: "RADIANT_AURA",
      tier: "large",
      distance: 350,
      angle: 273,
    },
    "30": {
      id: "30",
      type: "SUN_AURA",
      tier: "medium",
      distance: 420,
      angle: 273,
    },
    "31": { id: "31", type: "ATTR_SPIRIT", distance: 490, angle: 273 },
    "32": {
      id: "32",
      type: "LIGHTNING",
      tier: "medium",
      distance: 280,
      angle: 285,
    },
    "33": {
      id: "33",
      type: "SUBZERO",
      tier: "medium",
      distance: 280,
      angle: 293,
    },
    "34": {
      id: "34",
      type: "FROST",
      tier: "medium",
      distance: 350,
      angle: 293,
    },
    "35": { id: "35", type: "ATTR_INT", distance: 350, angle: 285 },
    "36": {
      id: "36",
      type: "WIZARD",
      tier: "medium",
      distance: 420,
      angle: 285,
    },
    "37": {
      id: "37",
      type: "DARK_ARTS",
      tier: "medium",
      distance: 490,
      angle: 282,
    },
    "38": {
      id: "38",
      type: "CHAIN_HIT",
      tier: "medium",
      distance: 490,
      angle: 288,
    },
    "39": {
      id: "39",
      type: "ABYSS",
      tier: "medium",
      distance: 560,
      angle: 282,
    },
    "40": {
      id: "40",
      type: "MASS_DESTRUCTION",
      tier: "medium",
      distance: 560,
      angle: 288,
    },
    "41": { id: "41", type: "ATTR_INT", distance: 630, angle: 285 },
    "42": { id: "42", type: "ATTR_INT", base: true, angle: 315 },
    "43": {
      id: "43",
      type: "HEALER",
      tier: "medium",
      distance: 70,
      angle: 315,
    },
    "44": {
      id: "44",
      type: "HEALER_II",
      tier: "medium",
      distance: 140,
      angle: 315,
    },
    "45": { id: "45", type: "ATTR_INT", distance: 210, angle: 315 },
    "46": {
      id: "46",
      type: "WATER_AURA",
      tier: "large",
      distance: 280,
      angle: 320,
    },
    "47": {
      id: "47",
      type: "HEALING_REVIVE",
      tier: "medium",
      distance: 280,
      angle: 310,
    },
    "48": {
      id: "48",
      type: "SHROUD_FILTER",
      tier: "medium",
      distance: 340,
      angle: 315,
    },
    "49": {
      id: "49",
      type: "WATERS_OF_LIFE",
      tier: "medium",
      distance: 330,
      angle: 325,
    },
    "50": { id: "50", type: "ATTR_SPIRIT", distance: 340, angle: 306 },
    "51": { id: "51", type: "ATTR_INT", distance: 410, angle: 312 },
    "52": { id: "52", type: "ATTR_SPIRIT", distance: 410, angle: 318 },
    "53": {
      id: "53",
      type: "MARTYR",
      tier: "large",
      distance: 480,
      angle: 315,
    },
    "55": { id: "55", type: "BLINK", tier: "large", distance: 120, angle: 330 },
    "56": {
      id: "56",
      type: "EMERGENCY_BLINK",
      tier: "medium",
      distance: 180,
      angle: 327,
    },
    "57": {
      id: "57",
      type: "BLINK_ATTACK",
      tier: "medium",
      distance: 180,
      angle: 333,
    },
    "62": { id: "62", type: "ATTR_SPIRIT", distance: 240, angle: 330 },
    "58": { id: "58", type: "ATTR_INT", base: true, angle: 345 },
    "59": {
      id: "59",
      type: "ARCANE_DEFLECTION",
      tier: "medium",
      distance: 70,
      angle: 345,
    },
    "60": {
      id: "60",
      type: "EVASION_ATTACK",
      tier: "large",
      distance: 120,
      angle: 360,
    },
    "61": {
      id: "61",
      type: "BATTLE_HEAL",
      tier: "medium",
      distance: 190,
      angle: 360,
    },
    "69": { id: "69", type: "ATTR_INT", distance: 140, angle: 345 },
    "70": { id: "70", type: "UNITY", tier: "large", distance: 210, angle: 345 },
    "72": {
      id: "72",
      type: "STING",
      tier: "medium",
      distance: 270,
      angle: 350,
    },
    "66": {
      id: "66",
      type: "LIFE_BURST",
      tier: "medium",
      distance: 330,
      angle: 354,
    },
    "71": {
      id: "71",
      type: "WAND_MASTER",
      tier: "medium",
      distance: 270,
      angle: 340,
    },
    "180": {
      id: "180",
      type: "ETERNAL_SPARK",
      tier: "medium",
      distance: 330,
      angle: 336,
    },
    "73": { id: "73", type: "ATTR_SPIRIT", distance: 350, angle: 348 },
    "74": { id: "74", type: "ATTR_INT", distance: 350, angle: 342 },
    "188": {
      id: "188",
      type: "LIFE_ESSENCES",
      tier: "large",
      distance: 420,
      angle: 345,
    },
    "54": { id: "54", type: "EXALTED", distance: 490, angle: 345 },
    "75": { id: "75", type: "ATTR_CONS", base: true, angle: 15 },
    "76": {
      id: "76",
      type: "SHINY_PLATES",
      tier: "medium",
      distance: 70,
      angle: 15,
    },
    "77": {
      id: "77",
      type: "HEAVY_PLATES",
      tier: "medium",
      distance: 140,
      angle: 15,
    },
    "78": {
      id: "78",
      type: "ATTR_CONS",
      tier: "small",
      distance: 210,
      angle: 15,
    },
    "79": { id: "79", type: "TOWER", tier: "medium", distance: 280, angle: 20 },
    "80": {
      id: "80",
      type: "WARDEN",
      tier: "medium",
      distance: 280,
      angle: 10,
    },
    "63": {
      id: "63",
      type: "ABSORB",
      tier: "medium",
      distance: 350,
      angle: 5,
    },
    "65": { id: "65", type: "SNAP", tier: "medium", distance: 420, angle: 5 },
    "67": {
      id: "67",
      type: "SOUL_LEECH",
      tier: "medium",
      distance: 490,
      angle: 5,
    },
    "81": { id: "81", type: "ATTR_STR", distance: 350, angle: 25 },
    "82": { id: "82", type: "ATTR_STR", distance: 350, angle: 18 },
    "83": { id: "83", type: "ATTR_CONS", distance: 350, angle: 12 },
    "84": {
      id: "84",
      type: "NEMESIS",
      tier: "large",
      distance: 420,
      angle: 25,
    },
    "85": {
      id: "85",
      type: "ARCH_NEMESIS",
      tier: "medium",
      distance: 490,
      angle: 25,
    },
    "86": {
      id: "86",
      type: "EARTH_AURA",
      tier: "large",
      distance: 480,
      angle: 15,
    },
    "87": { id: "87", type: "THICK_SKIN", distance: 550, angle: 15 },
    "88": { id: "88", type: "ATTR_CONS", base: true, angle: 45 },
    "89": {
      id: "89",
      type: "WARRIOR_PATH",
      tier: "medium",
      distance: 70,
      angle: 45,
    },
    "90": {
      id: "90",
      type: "PURIFICATION",
      tier: "medium",
      distance: 120,
      angle: 30,
    },
    "91": { id: "91", type: "ATTR_STR", distance: 140, angle: 45 },
    "92": {
      id: "92",
      type: "SLASHER",
      tier: "medium",
      distance: 210,
      angle: 55,
    },
    "93": { id: "93", type: "BRUTE", tier: "medium", distance: 210, angle: 45 },
    "94": {
      id: "94",
      type: "THRUST",
      tier: "medium",
      distance: 210,
      angle: 35,
    },
    "95": {
      id: "95",
      type: "BUTCHER",
      tier: "medium",
      distance: 280,
      angle: 55,
    },
    "96": {
      id: "96",
      type: "HAMMER_TIME",
      tier: "medium",
      distance: 280,
      angle: 45,
    },
    "97": {
      id: "97",
      type: "PIERCE",
      tier: "medium",
      distance: 280,
      angle: 35,
    },
    "98": {
      id: "98",
      type: "VETERAN",
      tier: "medium",
      distance: 350,
      angle: 45,
    },
    "99": { id: "99", type: "ATTR_CONS", distance: 420, angle: 50 },
    "100": { id: "100", type: "ATTR_STR", distance: 420, angle: 40 },
    "101": {
      id: "101",
      type: "SWIFT_BLADES",
      tier: "large",
      distance: 490,
      angle: 45,
    },
    "102": { id: "102", type: "ATTR_CONS", distance: 560, angle: 45 },
    "103": { id: "103", type: "ATTR_STR", base: true, angle: 75 },
    "104": {
      id: "104",
      type: "HEAVY_HANDED",
      tier: "medium",
      distance: 70,
      angle: 75,
    },
    "183": {
      id: "183",
      type: "STEADFAST",
      tier: "medium",
      distance: 120,
      angle: 90,
    },
    "105": { id: "105", type: "ATTR_STR", distance: 140, angle: 75 },
    "106": {
      id: "106",
      type: "FEAST",
      tier: "medium",
      distance: 120,
      angle: 60,
    },
    "107": { id: "107", type: "ATTR_CONS", distance: 210, angle: 75 },
    "108": {
      id: "108",
      type: "RELENTLESS",
      tier: "medium",
      distance: 280,
      angle: 80,
    },
    "109": {
      id: "109",
      type: "BREACH",
      tier: "medium",
      distance: 280,
      angle: 70,
    },
    "110": {
      id: "110",
      type: "SHOCKWAVE",
      tier: "large",
      distance: 350,
      angle: 60,
    },
    "111": { id: "111", type: "ATTR_CONS", distance: 380, angle: 75 },
    "112": {
      id: "112",
      type: "HEAVY_SPECIALIZATION",
      tier: "large",
      distance: 450,
      angle: 75,
    },
    "113": { id: "113", type: "BARBARIAN", distance: 520, angle: 75 },
    "114": {
      id: "114",
      type: "BLOOD_RAGE",
      tier: "medium",
      distance: 590,
      angle: 75,
    },
    "115": { id: "115", type: "ATTR_STR", base: true, angle: 105 },
    "116": {
      id: "116",
      type: "JUMP_ATTACK",
      tier: "large",
      distance: 70,
      angle: 105,
    },
    "117": {
      id: "117",
      type: "DOUBLE_JUMP",
      tier: "large",
      distance: 120,
      angle: 120,
    },
    "118": {
      id: "118",
      type: "JUMP_ATTACK_II",
      tier: "medium",
      distance: 190,
      angle: 120,
    },
    "119": { id: "119", type: "ATTR_STR", distance: 190, angle: 105 },
    "120": {
      id: "120",
      type: "BLOOD_WARRIOR",
      tier: "medium",
      distance: 340,
      angle: 105,
    },
    "182": {
      id: "182",
      type: "FINESSE",
      tier: "medium",
      distance: 260,
      angle: 110,
    },
    "178": {
      id: "178",
      type: "BACKSTAB_MASTERY",
      tier: "medium",
      distance: 310,
      angle: 120,
    },
    "121": {
      id: "121",
      type: "VIGOROUS_DEFLECTION",
      tier: "medium",
      distance: 260,
      angle: 100,
    },
    "122": { id: "122", type: "ATTR_CONS", distance: 470, angle: 105 },
    "123": { id: "123", type: "ATTR_CONS", distance: 400, angle: 110 },
    "124": { id: "124", type: "ATTR_STR", distance: 400, angle: 100 },
    "125": { id: "125", type: "BASH", tier: "large", distance: 310, angle: 90 },
    "126": { id: "126", type: "ATTR_STR", distance: 380, angle: 90 },
    "127": { id: "127", type: "ATTR_ENDURANCE", base: true, angle: 135 },
    "128": {
      id: "128",
      type: "RUNNER",
      tier: "medium",
      distance: 70,
      angle: 135,
    },
    "129": {
      id: "129",
      type: "INNER_FIRES",
      tier: "medium",
      distance: 120,
      angle: 150,
    },
    "179": {
      id: "179",
      type: "RELENTLESS_FLAME",
      tier: "medium",
      distance: 190,
      angle: 150,
    },
    "130": { id: "130", type: "ATTR_ENDURANCE", distance: 140, angle: 135 },
    "131": {
      id: "131",
      type: "WANDERLUST",
      tier: "medium",
      distance: 210,
      angle: 135,
    },
    "132": {
      id: "132",
      type: "GOOD_METABOLISM",
      tier: "medium",
      distance: 280,
      angle: 140,
    },
    "133": {
      id: "133",
      type: "SWIFTSHOT_SUSTENANCE",
      tier: "medium",
      distance: 280,
      angle: 130,
    },
    "134": { id: "134", type: "REBOUND", distance: 320, angle: 135 },
    "135": {
      id: "135",
      type: "SWEET_TOOTH",
      tier: "medium",
      distance: 370,
      angle: 140,
    },
    "136": {
      id: "136",
      type: "ARACHNOID",
      tier: "medium",
      distance: 370,
      angle: 130,
    },
    "137": { id: "137", type: "ATTR_DEX", distance: 440, angle: 135 },
    "138": {
      id: "138",
      type: "DESSERT_STOMACH",
      tier: "large",
      distance: 510,
      angle: 135,
    },
    "139": { id: "139", type: "ATTR_ENDURANCE", distance: 580, angle: 135 },
    "140": { id: "140", type: "ATTR_ENDURANCE", base: true, angle: 165 },
    "141": {
      id: "141",
      type: "SNAKE_EATER",
      tier: "medium",
      distance: 70,
      angle: 165,
    },
    "142": {
      id: "142",
      type: "EAGLE_EYE",
      tier: "large",
      distance: 120,
      angle: 180,
    },
    "143": {
      id: "143",
      type: "MITHRIDATIST",
      tier: "medium",
      distance: 140,
      angle: 165,
    },
    "144": { id: "144", type: "ATTR_ENDURANCE", distance: 210, angle: 165 },
    "184": {
      id: "184",
      type: "DAGGER_MASTER",
      tier: "medium",
      distance: 280,
      angle: 160,
    },
    "189": {
      id: "189",
      type: "POISONED_BLADES",
      tier: "medium",
      distance: 350,
      angle: 153,
    },
    "190": {
      id: "190",
      type: "POISON_MASTERY",
      tier: "medium",
      distance: 420,
      angle: 153,
    },
    "185": {
      id: "185",
      type: "SLICE_AND_DICE",
      tier: "medium",
      distance: 280,
      angle: 170,
    },
    "191": {
      id: "191",
      type: "QUICK_REFLEX_BLOCK",
      tier: "medium",
      distance: 350,
      angle: 177,
    },
    "145": {
      id: "145",
      type: "VUKAH_LANGUAGE",
      tier: "medium",
      distance: 420,
      angle: 170,
    },
    "146": {
      id: "146",
      type: "CALM_SPIRIT",
      tier: "medium",
      distance: 420,
      angle: 160,
    },
    "147": { id: "147", type: "ATTR_DEX", distance: 350, angle: 168 },
    "148": { id: "148", type: "ATTR_ENDURANCE", distance: 350, angle: 162 },
    "149": {
      id: "149",
      type: "VUKAH_CULTURE",
      tier: "medium",
      distance: 510,
      angle: 170,
    },
    "150": {
      id: "150",
      type: "BEAST_MASTER",
      tier: "medium",
      distance: 510,
      angle: 160,
    },
    "151": { id: "151", type: "ATTR_DEX", distance: 465, angle: 165 },
    "152": {
      id: "152",
      type: "ENDURANCE_OF_THE_FLAME",
      distance: 580,
      angle: 165,
    },
    "153": { id: "153", type: "ATTR_DEX", base: true, angle: 195 },
    "154": {
      id: "154",
      type: "MARKSMAN",
      tier: "medium",
      distance: 70,
      angle: 195,
    },
    "155": {
      id: "155",
      type: "SILENT_STRIDE",
      tier: "medium",
      distance: 120,
      angle: 210,
    },
    "156": {
      id: "156",
      type: "SHARPSHOOTER",
      tier: "medium",
      distance: 200,
      angle: 200,
    },
    "157": {
      id: "157",
      type: "COUNTER_BATTERY",
      tier: "medium",
      distance: 200,
      angle: 190,
    },
    "158": {
      id: "158",
      type: "EAGLES_BANE",
      tier: "medium",
      distance: 320,
      angle: 200,
    },
    "159": {
      id: "159",
      type: "SKILL_SHOT",
      tier: "medium",
      distance: 320,
      angle: 190,
    },
    "160": {
      id: "160",
      type: "BEE_STING",
      tier: "large",
      distance: 400,
      angle: 205,
    },
    "161": {
      id: "161",
      type: "RANGER",
      tier: "medium",
      distance: 420,
      angle: 195,
    },
    "162": {
      id: "162",
      type: "MULTI_SHOT",
      tier: "large",
      distance: 400,
      angle: 185,
    },
    "186": {
      id: "186",
      type: "MULTI_SHOT_SPREAD",
      tier: "medium",
      distance: 470,
      angle: 183,
    },
    "187": {
      id: "187",
      type: "MULTI_SHOT_TRIGGER",
      tier: "medium",
      distance: 530,
      angle: 185,
    },
    "163": { id: "163", type: "ATTR_DEX", base: true, angle: 225 },
    "164": {
      id: "164",
      type: "AIRBORNE",
      tier: "medium",
      distance: 70,
      angle: 225,
    },
    "165": {
      id: "165",
      type: "UPDRAFT",
      tier: "large",
      distance: 120,
      angle: 240,
    },
    "166": { id: "166", type: "ATTR_ENDURANCE", distance: 140, angle: 225 },
    "167": {
      id: "167",
      type: "SNIPER",
      tier: "medium",
      distance: 210,
      angle: 225,
    },
    "168": {
      id: "168",
      type: "VITALITY_SURGE",
      tier: "medium",
      distance: 280,
      angle: 230,
    },
    "169": {
      id: "169",
      type: "BLESSED_ARROWS",
      tier: "medium",
      distance: 280,
      angle: 220,
    },
    "170": { id: "170", type: "ATTR_DEX", distance: 350, angle: 235 },
    "171": {
      id: "171",
      type: "SHELL_SHOCK",
      tier: "large",
      distance: 420,
      angle: 235,
    },
    "172": {
      id: "172",
      type: "BOUNTY_BONANZA",
      tier: "medium",
      distance: 350,
      angle: 225,
    },
    "173": { id: "173", type: "ATTR_DEX", distance: 350, angle: 215 },
    "174": {
      id: "174",
      type: "RICOCHETS",
      tier: "medium",
      distance: 420,
      angle: 225,
    },
    "175": { id: "175", type: "GRACEFUL_STRIDE", distance: 490, angle: 225 },
    "176": { id: "176", type: "ATTR_ENDURANCE", distance: 490, angle: 220 },
    "177": {
      id: "177",
      type: "CHAIN_REACTION",
      tier: "medium",
      distance: 560,
      angle: 225,
    },
    "192": {
      id: "192",
      type: "GIANT_SLAYER_HOOK",
      base: true,
      tier: "large",
      distance: -100,
      angle: 285,
    },
    "193": {
      id: "193",
      type: "GROUNDING_HOOK",
      tier: "large",
      distance: -180,
      angle: 295,
    },
  },
  edges: {
    "1": [],
    "2": ["3"],
    "3": ["2", "181"],
    "181": ["3", "9"],
    "4": ["5", "6"],
    "5": ["4", "7"],
    "6": ["4", "7"],
    "7": ["5", "6"],
    "8": ["9"],
    "9": ["8", "181"],
    "10": [],
    "11": ["12"],
    "12": ["11", "13", "14", "20", "165"],
    "13": ["12", "15"],
    "14": ["12", "15"],
    "15": ["13", "14", "16", "17"],
    "16": ["15", "18", "64"],
    "17": ["15", "68", "64"],
    "18": ["16", "19"],
    "19": ["18", "68"],
    "20": ["12", "22"],
    "21": ["22"],
    "22": ["20", "24", "23", "21"],
    "23": ["22", "43"],
    "24": ["22", "25", "26", "27"],
    "25": ["24", "28"],
    "26": ["24", "32"],
    "27": ["24", "33"],
    "28": ["25", "29", "35"],
    "29": ["28", "30"],
    "30": ["29", "31"],
    "31": ["30"],
    "32": ["26", "35"],
    "33": ["27", "35", "34"],
    "34": ["33"],
    "35": ["28", "32", "33", "36"],
    "36": ["35", "37", "38"],
    "37": ["36", "39"],
    "38": ["36", "40"],
    "39": ["37"],
    "40": ["38", "41"],
    "41": ["40"],
    "42": ["43"],
    "43": ["42", "23", "44", "55"],
    "44": ["43", "45"],
    "45": ["44", "47", "48", "46"],
    "46": ["45", "49", "52"],
    "47": ["45", "50", "51"],
    "48": ["45"],
    "49": ["46"],
    "50": ["47"],
    "51": ["47", "53"],
    "52": ["46", "53"],
    "53": ["51", "52"],
    "54": ["188"],
    "55": ["43", "56", "57", "59"],
    "56": ["55", "62"],
    "57": ["55", "62"],
    "58": ["59"],
    "59": ["58", "55", "69", "60"],
    "60": ["59", "76", "61"],
    "61": ["60"],
    "62": ["56", "57"],
    "63": ["65"],
    "64": ["16", "17"],
    "65": ["63", "67"],
    "66": ["72"],
    "67": ["65"],
    "68": ["17", "19"],
    "69": ["59", "70"],
    "70": ["69", "72", "73", "71", "74"],
    "71": ["70", "180"],
    "72": ["70", "66"],
    "73": ["70", "188"],
    "74": ["70", "188"],
    "75": ["76"],
    "76": ["75", "60", "77", "90"],
    "77": ["76", "78"],
    "78": ["77", "80", "79"],
    "79": ["78", "81", "82"],
    "80": ["78", "83", "63"],
    "81": ["79", "84"],
    "82": ["79", "86"],
    "83": ["80", "86"],
    "84": ["81", "85"],
    "85": ["84"],
    "86": ["82", "83", "87"],
    "87": ["86"],
    "88": ["89"],
    "89": ["88", "90", "91", "106"],
    "90": ["89", "76"],
    "91": ["89", "92", "93", "94"],
    "92": ["91", "95"],
    "93": ["91", "96"],
    "94": ["91", "97"],
    "95": ["92", "98"],
    "96": ["93", "98"],
    "97": ["94", "98"],
    "98": ["95", "96", "97", "99", "101", "100"],
    "99": ["98"],
    "100": ["98"],
    "101": ["98", "102"],
    "102": ["101"],
    "103": ["104"],
    "104": ["103", "106", "105", "183"],
    "183": ["104", "116"],
    "105": ["104", "107"],
    "106": ["104", "89"],
    "107": ["105", "108", "109"],
    "108": ["107", "111", "125"],
    "109": ["107", "111", "110"],
    "110": ["109"],
    "111": ["108", "109", "112"],
    "112": ["111", "113"],
    "113": ["112", "114"],
    "114": ["113"],
    "115": ["116"],
    "116": ["115", "117", "119", "183"],
    "117": ["116", "118", "128"],
    "118": ["117"],
    "119": ["116", "182", "121"],
    "120": ["182", "121", "123", "124"],
    "182": ["119", "178", "120"],
    "121": ["119", "125", "120"],
    "122": ["123", "124"],
    "123": ["122", "120"],
    "124": ["122", "120"],
    "125": ["121", "108", "126"],
    "126": ["125"],
    "127": ["128"],
    "128": ["127", "117", "130", "129"],
    "129": ["128", "141", "179"],
    "130": ["128", "131"],
    "131": ["130", "132", "133"],
    "132": ["131", "135", "134"],
    "133": ["131", "136", "178"],
    "134": ["132"],
    "135": ["132", "137"],
    "136": ["133", "137"],
    "137": ["135", "136", "138"],
    "138": ["137", "139"],
    "139": ["138"],
    "140": ["141"],
    "141": ["140", "129", "143", "142"],
    "142": ["141", "154"],
    "143": ["141", "144"],
    "144": ["143", "185", "184"],
    "184": ["144", "148", "189"],
    "185": ["144", "147", "191"],
    "145": ["147", "151", "149"],
    "146": ["148", "151", "150"],
    "147": ["145", "185"],
    "148": ["184", "146"],
    "149": ["145", "152"],
    "150": ["146", "152"],
    "151": ["145", "146"],
    "152": ["149", "150"],
    "153": ["154"],
    "154": ["153", "142", "155", "156", "157"],
    "155": ["154", "164"],
    "156": ["154", "159"],
    "157": ["154", "158"],
    "158": ["157", "160", "161"],
    "159": ["156", "161", "162"],
    "160": ["158"],
    "161": ["158", "159"],
    "162": ["159", "186"],
    "186": ["162", "187"],
    "187": ["186"],
    "163": ["164"],
    "164": ["163", "165", "166", "155"],
    "165": ["164", "12"],
    "166": ["164", "167"],
    "167": ["166", "168", "169"],
    "168": ["167", "170", "172"],
    "169": ["167", "172", "173"],
    "170": ["168", "171"],
    "171": ["170"],
    "172": ["168", "169", "174"],
    "173": ["169"],
    "174": ["175", "176", "172"],
    "175": ["174", "177"],
    "176": ["174"],
    "177": ["175"],
    "178": ["182", "133"],
    "179": ["129"],
    "180": ["71"],
    "188": ["54", "73", "74"],
    "189": ["184", "190"],
    "190": ["189"],
    "191": ["185"],
    "192": ["193"],
    "193": ["192"],
  },
};

export default SkillNodes;
