export type Node = {
  id: string;
  type: string;
  base?: boolean;
  tier?: "small" | "medium" | "large";
  angle?: number;
  distance?: number;
};

export type NodeTypeMetadata = {
  name: string;
  description: string[];
  hasAsset?: boolean;
  unselectedAsset?: string;
  selectableAsset?: string;
  selectedAsset?: string;
  color: string;
  cost: number;
};

export type SkillNodesType = {
  types: { [key: string]: NodeTypeMetadata };
  nodes: { [key: string]: Node };
  edges: { [key: string]: string[] };
};

// ANGLE LINES
export const LinesAngles = [
  15, 45, 75, 105, 135, 165, 195, 225, 255, 285, 315, 345,
];

const SHROUD_TIME_TEXT =
  "<h4>Shroud Time</h4><br>Should this time run out, the Shroud will consume you.";

const SkillNodes: SkillNodesType = {
  types: {
    SAVIOUR: {
      name: "SAVIOUR",
      description: [
        "You only need 3 instead of 6 seconds to <b>revive an ally</b>.",
      ],
      color: "gold",
      cost: 2,
    },
    BACKSTAB_DAMAGE: {
      name: "BACKSTAB_DAMAGE",
      description: ["Increase the damage you deal from behind by 25%."],
      color: "gold",
      cost: 2,
    },
    MINER: {
      name: "MINER",
      description: [
        "When you mine resources, you have a 10% chance to get one additional resource.",
      ],
      color: "gold",
      cost: 4,
    },
    LUMBERJACK: {
      name: "LUMBERJACK",
      description: [
        "Felling axes do 30% more dmaage against wooden objects including trees.",
      ],
      color: "gold",
      cost: 2,
    },
    QUALITY_GEAR: {
      name: "QUALITY_GEAR",
      description: ["All tools lose durability 50% slower."],
      color: "gold",
      cost: 2,
    },
    MASON: {
      name: "MASON",
      description: [
        "The Pickaxe deals 30% more damage against stone objects, including resource veins.",
      ],
      color: "gold",
      cost: 2,
    },
    POWER_PARRY: {
      name: "POWER_PARRY",
      description: [
        "Increases the enemy's stun bar gain on parry attacks.",
        "<b>Parry</b><br>While equipped with a shield, press <b>[RMB] to block</b>. A well-timed block willl <b>parry</b> the attack.",
      ],
      color: "gold",
      cost: 2,
    },
    ATTR_SPIRIT: {
      name: "SPIRIT",
      description: [
        "Increases your Spirit attribute by 1",
        "Increases Mana by 20 per Attribute Point",
      ],
      color: "blue",
      cost: 1,
    },
    ATTR_INT: {
      name: "INTELLIGENCE",
      description: [
        "Increases your Intelligence attribute by 1",
        "Increases Magic damage by 5% per Attribute Point",
      ],
      color: "blue",
      cost: 1,
    },
    ATTR_CONS: {
      name: "CONSTITUTION",
      description: [
        "Increases your Constitution attribute by 1",
        "Increases Health by 50 per Attribute Point",
      ],
      color: "red",
      cost: 1,
    },
    ATTR_STR: {
      name: "STRENGTH",
      description: [
        "Increases your Strength attribute by 1",
        "Increases Melee damage by 5% per Attribute Point",
      ],
      color: "red",
      cost: 1,
    },
    ATTR_ENDURANCE: {
      name: "ENDURANCE",
      description: [
        "Increases your Endurance attribute by 1",
        "Increases Stamina by 10 per Attribute Point",
      ],
      color: "green",
      cost: 1,
    },
    ATTR_DEX: {
      name: "DEXTERITY",
      description: [
        "Increases your Dexterity attribute by 1",
        "Increases Ranged damage by 5% per Attribute Point",
      ],
      color: "green",
      cost: 1,
    },
    WELL_RESTED: {
      name: "WELL RESTED",
      description: [
        "The base duration for the Rested buff is increased by 5 Minutes.",
        "Increase the Confort in your home to further increase the duration.",
      ],
      color: "gold",
      cost: 1,
    },
    SNEAK_ATTACK: {
      name: "SNEAK ATTACK",
      description: [
        "The <b>Sneak Attack</b> deals massive 10x damage to unaware enemies.",
        "To trigger it, sneak up on an enemy and press <b>[E]</b>.",
      ],
      hasAsset: true,
      selectableAsset: "sneak_attack_1.png",
      selectedAsset: "sneak_attack_2.png",
      color: "gold",
      cost: 3,
    },
    MERCILESS_ATTACK: {
      name: "MERCILESS ATTACK",
      description: [
        "Perform a Merciless Attack by pressing [E] to deal massive damage to an enemy you've empowered.",
        "<b>Overpower</b><br>To overpower an enemy, fill their stun bar by attacking while they block or by parrying their attacks.",
      ],
      hasAsset: true,
      selectableAsset: "merciless_attack_1.png",
      selectedAsset: "merciless_attack_2.png",
      color: "gold",
      cost: 2,
    },
    UPDRAFT: {
      name: "UPDRAFT",
      description: [
        "Pressing the jump button while gliding will give you a small height boost. This skill can be used once per flight. Cost: 120 mana",
      ],
      hasAsset: true,
      color: "green",
      cost: 4,
    },
    BEGONE: {
      name: "BEGONE",
      description: [
        "A magic-powered punch that pushes and stuns hit foes.",
        "Replaces your unarmed attacks as long as you have the necessary mana available: <b>30 Mana</b>",
      ],
      hasAsset: true,
      color: "blue",
      cost: 3,
    },
    RADIANT_AURA: {
      name: "RADIANT AURA",
      description: [
        "All Fell foes within 10 meters take 1 fire damage per intelligence per second.",
      ],
      hasAsset: true,
      color: "blue",
      cost: 3,
    },
    WATER_AURA: {
      name: "WATER AURA",
      description: [
        "You emit a healing aura. It heals all injured allies within 15 meters. The healing scales with your intelligence attribute (1 health for every 2 points of intelligence).",
      ],
      hasAsset: true,
      color: "blue",
      cost: 3,
    },
    MARTYR: {
      name: "MARTYR",
      description: [
        "When you are killed by an enemy, all allies within 50 meters will heal 30% of their maximum health.",
      ],
      hasAsset: true,
      color: "blue",
      cost: 5,
    },
    BLINK: {
      name: "BLINK",
      description: [
        "Replaces the Dodge Roll ability with a short range teleport.",
      ],
      hasAsset: true,
      color: "blue",
      cost: 4,
    },
    EVASION_ATTACK: {
      name: "EVASION ATTACK",
      description: [
        "When equipped with a melee weapon, you can perform an evade attack which dashes towards the enemy and deals more weapon damage with <b>[LMB]</b>",
      ],
      hasAsset: true,
      color: "red",
      cost: 4,
    },
    EARTH_AURA: {
      name: "EARTH AURA",
      description: [
        "All damage against players within 10 meters is reduced by 10%",
      ],
      hasAsset: true,
      color: "red",
      cost: 5,
    },
    NEMESIS: {
      name: "NEMESIS",
      description: [
        "Whenever an ally draws the attention of an enemy, you draw it in equal measures.",
      ],
      hasAsset: true,
      color: "red",
      cost: 5,
    },
    SHOCKWAVE: {
      name: "SHOCKWAVE",
      description: [
        "Overpower an enemy to trigger a shock-wave that increases nearby enemies stun bar and pushes them back.",
        "<b>Overpower</b><br>To overpower an enemy, fill their stun bar by attacking while they block or by parrying their attacks.",
      ],
      hasAsset: true,
      color: "red",
      cost: 3,
    },
    HEAVY_SPECIALIZATION: {
      name: "HEAVY SPECIALIZATION",
      description: ["Allows you to attack faster with two-handed hammers."],
      hasAsset: true,
      color: "red",
      cost: 5,
    },
    BASH: {
      name: "BASH",
      description: ["You parry bashes the enemy for 20 blunt damage."],
      hasAsset: true,
      color: "red",
      cost: 5,
    },
    JUMP_ATTACK: {
      name: "JUMP ATTACK",
      description: [
        "When equipped with a melee weapon, you can perform a jump attack which deals 50% more weapon damage in a small blast radius.",
        "Costs stamina appropriately to the weapon's weight. Does not work with toools.",
      ],
      hasAsset: true,
      color: "red",
      cost: 3,
    },
    DOUBLE_JUMP: {
      name: "DOUBLE JUMP",
      description: ["Allows jumping a second time while airborne."],
      hasAsset: true,
      color: "green",
      cost: 4,
    },
    DESSERT_STOMACH: {
      name: "DESSERT STOMACH",
      description: ["You gain one additional food slot"],
      hasAsset: true,
      color: "green",
      cost: 4,
    },
    EAGLE_EYE: {
      name: "EAGLE EYE",
      description: [
        "Greatly increases the zoom while aiming with a bow.",
        "To aim, gold down the [RMB] while a bow is selected in the Action bar. (Alternatively, gold [Q] to aim your equipped bow.)",
      ],
      hasAsset: true,
      color: "green",
      cost: 3,
    },
    MULTI_SHOT: {
      name: "MULTI SHOT",
      description: [
        "Adds a 20% chance to spawn a flurry of arrows that spread slightly",
      ],
      hasAsset: true,
      color: "green",
      cost: 3,
    },
    BEE_STING: {
      name: "BEE STING",
      description: [
        "You can draw and use your bow while gliding. You will fall slowly.",
        "Cost: 10 stamina per second",
      ],
      hasAsset: true,
      color: "green",
      cost: 3,
    },
    SHELL_SHOCK: {
      name: "SHELL SHOCK",
      description: [
        "Influse your <i>ranged explosives</i> with mana. They now stun enemies for up to 1 second.",
        "Mana Cost: 5 per stunned enemy",
      ],
      hasAsset: true,
      color: "green",
      cost: 5,
    },
    COUNTERSTRIKE: {
      name: "COUNTERSTRIKE",
      description: [
        "After receiving damage there is a 20% chance to <b>reflect</b> 50% of the damage back to the attacker as fire damage.",
        "This magical attack can trigger other skills.",
      ],
      color: "blue",
      cost: 2,
    },
    TERROR: {
      name: "TERROR",
      description: [
        "On a critical hit with a spell, the target will be stunned for 4 seconds.",
      ],
      color: "blue",
      cost: 4,
    },
    QUICK_CHARGE: {
      name: "QUICK CHARGE",
      description: [
        "Reduces the time Staffs require to charge-up a spell by 50%.",
      ],
      color: "blue",
      cost: 3,
    },
    THIS_IS_THE_WAY: {
      name: "THIS IS THE WAY",
      description: [
        "When attacking with a magical weapon all damage is increased by 10%.",
      ],
      color: "blue",
      cost: 2,
    },
    ARSONIST: {
      name: "ARSONIST",
      description: ["All fire damage is increased by an additional 10%."],
      color: "blue",
      cost: 2,
    },
    PYROMANIAC: {
      name: "PYROMANIAC",
      description: ["All fire damage is increased by an additional 20%."],
      color: "blue",
      cost: 3,
    },
    SUN_AURA: {
      name: "SUN AURA",
      description: [
        "All Fell foes within 10 meters take 1 additional fire damage per intelligence per second.",
      ],
      color: "blue",
      cost: 2,
    },
    THUNDER: {
      name: "THUNDER",
      description: ["All shock damage is increased by aan additional 10%."],
      color: "blue",
      cost: 2,
    },
    LIGHTNING: {
      name: "LIGHTNING",
      description: ["All shock damage is increased by aan additional 20%."],
      color: "blue",
      cost: 3,
    },
    ICEMAN: {
      name: "ICEMAN",
      description: ["All ice damage is increased by aan additional 10%."],
      color: "blue",
      cost: 2,
    },
    SUBZERO: {
      name: "SUBZERO",
      description: ["All ice damage is increased by aan additional 20%."],
      color: "blue",
      cost: 3,
    },
    FROST: {
      name: "FROST",
      description: [
        "When receiving melee damage, the attacker will be slowed down for 3 seconds.",
      ],
      color: "blue",
      cost: 3,
    },
    WIZARD: {
      name: "WIZARD",
      description: [
        "When attacking with a magical weapon your critical hit chance is increased by 10%",
      ],
      color: "blue",
      cost: 3,
    },
    DARK_ARTS: {
      name: "DARK ARTS",
      description: ["All Shrouded damage is increased by aan additional 10%."],
      color: "blue",
      cost: 3,
    },
    ABYSS: {
      name: "ABYSS",
      description: ["All Shrouded damage is increased by aan additional 20%."],
      color: "blue",
      cost: 4,
    },
    CHAIN_HIT: {
      name: "CHAIN HIT",
      description: [
        "On a critical hit with a magical weapon, the attack will automatically hit a second enemy within 15 meters for 5 Shock damage per intelligence.",
      ],
      color: "blue",
      cost: 3,
    },
    MASS_DESTRUCTION: {
      name: "MASS DESTRUCTION",
      description: [
        "A critical attack with a magic weapon will hit all enemies within 20 meters of the target for 2 Shock damage per intelligence.",
      ],
      color: "blue",
      cost: 4,
    },
    NECROMANCER: {
      name: "NECROMANCER",
      description: [
        "When killing an enemy with a magic weapon, you have a 10% chance to summon a friendly skull companion.",
      ],
      color: "blue",
      cost: 3,
    },
    HEALER: {
      name: "HEALER",
      description: [
        "Health gain from healing spells will be increased by 10%.",
      ],
      color: "blue",
      cost: 2,
    },
    HEALER_II: {
      name: "HEALER_II",
      description: ["Health gain from healing spells will be increased by 20%"],
      color: "blue",
      cost: 2,
    },
    HEALING_REVIVE: {
      name: "HEALING REVIVE",
      description: [
        "Revived players will heal 25% of their health instead of 10%.",
      ],
      color: "blue",
      cost: 2,
    },
    SHROUD_FILTER: {
      name: "SHROUD FILTER",
      description: [
        "Dealing magic weapon damage has a 15% chance to trigger a small flmae brust that restores 30 seconds of <i>Shroud Time</i> to you and your allies within 20 meters.",
        SHROUD_TIME_TEXT,
      ],
      color: "blue",
      cost: 3,
    },
    WATERS_OF_LIFE: {
      name: "WATERS OF LIFE",
      description: [
        "Increases <b>Water Aura</b> healing to 2 health for every 2 points of intelligence.",
      ],
      color: "blue",
      cost: 2,
    },
    EMERGENCY_BLINK: {
      name: "EMERGENCY BLINK",
      description: [
        "You can blink while being stunned. This will break the stunned state.",
      ],
      color: "blue",
      cost: 2,
    },
    BLINK_ATTACK: {
      name: "BLINK ATTACK",
      description: [
        "Blinking into an enemy triggers an explosion which deals fire damage in a small range.",
        "Damage and mana cost scale with the intelligence attribute.",
      ],
      color: "blue",
      cost: 2,
    },
    ARCANE_DEFLECTION: {
      name: "ARCANE DEFLECTION",
      description: ["On a successful parry, gain 20 mana."],
      color: "blue",
      cost: 3,
    },
    UNITY: {
      name: "UNITY",
      description: [
        "Damaging enemies with wands has a 24$ chance to recover 2% mana.",
      ],
      color: "blue",
      cost: 3,
    },
    WAND_MASTER: {
      name: "WAND MASTER",
      description: ["30% Chance to spawn an additional wand projectile."],
      color: "blue",
      cost: 2,
    },
    STING: {
      name: "STING",
      description: ["Repeated wand damage is increased by 20%."],
      color: "blue",
      cost: 2,
    },
    BATTLE_HEAL: {
      name: "BATTLE HEAL",
      description: [
        "When dealing critical damage with a melee weapon, you will heal 5% of your maximum health.",
      ],
      color: "red",
      cost: 3,
    },
    BLOODLETTING: {
      name: "BLOODLETTING",
      description: [
        "When scoring a critical hit with a magical weapon, there is a 50% chance to spawn 2 health, mana, and/or stamina Orbs.",
        "Gathering the Orb replenishes 10% of the respective resource.",
      ],
      color: "blue",
      cost: 3,
    },
    LIFE_BURST: {
      name: "LIFE_BURST",
      description: [
        "When killing an enemy with a magic weapon all players within 15 meters of the target gain health equal to 3 times yoour Intelligence.",
      ],
      color: "blue",
      cost: 4,
    },
    BLOOD_MAGIC: {
      name: "BLOOD_MAGIC",
      description: [
        "When your mana drops below 20%, your restore 20% of your max mana at the cost of 1 health per mana. This will stop at 1 health.",
      ],
      color: "blue",
      cost: 4,
    },
    ABSORB: {
      name: "ABSORB",
      description: [
        "When you suffer magical damage, you have a 10% chance to generate 1 mana for each health point lost.",
      ],
      color: "red",
      cost: 3,
    },
    SNAP: {
      name: "SNAP",
      description: ["Restores 10% mana when triggering the Merciless Attack."],
      color: "red",
      cost: 4,
    },
    SOUL_LEECH: {
      name: "SOUL_LEECH",
      description: [
        "When killing an enemy with a melee weapon all players within 15 meters of the target gain 20 mana.",
      ],
      color: "red",
      cost: 4,
    },
    SHINY_PLATES: {
      name: "SHINY_PLATES",
      description: ["Physical armor gains 10% more armor points."],
      color: "red",
      cost: 2,
    },
    HEAVY_PLATES: {
      name: "HEAVY_PLATES",
      description: [
        "The maximum amount of physical damage your armor is able to mitigate is increased by 10%",
      ],
      color: "red",
      cost: 2,
    },
    WARDEN: {
      name: "WARDEN",
      description: [
        "When there are three or more enemies within 20 meters yoou suffer 15% less magical damage.",
      ],
      color: "red",
      cost: 3,
    },
    TOWER: {
      name: "TOWER",
      description: [
        "When there are three or more enemies within 20 meters you suffer 10% less physical damage.",
      ],
      color: "red",
      cost: 3,
    },
    ARCH_NEMESIS: {
      name: "ARCH_NEMESIS",
      description: [
        "Whenever an ally draws the attention of an enemy, you draw twice as much.",
      ],
      color: "red",
      cost: 3,
    },
    PURIFICATION: {
      name: "PURIFICATION",
      description: [
        "After defeating a Shroud infested foe with a melee weapon you replenish +5 seconds of Shroud Time.",
        SHROUD_TIME_TEXT,
      ],
      color: "red",
      cost: 3,
    },
    WARRIOR_PATH: {
      name: "THE WARRIOR'S PATH",
      description: [
        "When attacking with a melee weapon all damage is increased by 10%.",
      ],
      color: "red",
      cost: 2,
    },
    THRUST: {
      name: "THRUST",
      description: [
        "All melee piercing damage is increased by an additional 10%.",
      ],
      color: "red",
      cost: 2,
    },
    PIERCE: {
      name: "PIERCE",
      description: [
        "All melee piercing damage is increased by an additional 20%.",
      ],
      color: "red",
      cost: 3,
    },
    BRUTE: {
      name: "BRUTE",
      description: [
        "All melee blunt damage is increased by an additional 10%.",
      ],
      color: "red",
      cost: 2,
    },
    HAMMER_TIME: {
      name: "HAMMER TIME",
      description: [
        "All melee blunt damage is increased by an additional 20%.",
      ],
      color: "red",
      cost: 3,
    },
    SLASHER: {
      name: "SLASHER",
      description: [
        "All melee cutting damage is increased by an additional 10%.",
      ],
      color: "red",
      cost: 2,
    },
    BUTCHER: {
      name: "BUTCHER",
      description: [
        "All melee cutting damage is increased by an additional 20%.",
      ],
      color: "red",
      cost: 3,
    },
    VETERAN: {
      name: "VETERAN",
      description: [
        "When attacking with a melee weapon your critical hit chance is increased by 10%.",
      ],
      color: "red",
      cost: 4,
    },
    SWIFT_BLADES: {
      name: "SWIFT BLADES",
      description: [
        "Allows you to attack faster with one-handed swords and axes.",
      ],
      color: "red",
      cost: 5,
    },
    FEAST: {
      name: "FEAST",
      description: ["Meat now increases health by an additional 15%."],
      color: "red",
      cost: 3,
    },
    HEAVY_HANDED: {
      name: "HEAVY_HANDED",
      description: [
        "An enemy's stun bar is increased by an additional 20% when attacking into their block with a melee weapon.",
      ],
      color: "red",
      cost: 2,
    },
    BREACH: {
      name: "BREACH",
      description: [
        "When you break a block with melee attacks, the target will suffer 100% more melee damage for 2 seconds.",
      ],
      color: "red",
      cost: 3,
    },
    RELENTLESS: {
      name: "RELENTLESS",
      description: [
        "Dealing critical damage with a two-handed weapon increases your critical chance by another 10% for the next hit.",
      ],
      color: "red",
      cost: 5,
    },
    BARBARIAN: {
      name: "BARBARIAN",
      description: [
        "You will gain one strength level for every two levels of the Flame.",
      ],
      color: "red",
      cost: 5,
    },
    BLOOD_RAGE: {
      name: "BLOOD RAGE",
      description: [
        "When an enemy is killed within 10 meters with a melee weapon, the damage done with a melee weapons is increased by 20% for 10 seconds.",
      ],
      color: "red",
      cost: 5,
    },
    VIGOROUS_DEFLECTION: {
      name: "VIGOROUS DEFLECTION",
      description: ["You gain 30 stamina when you parry an enemy's attack."],
      color: "red",
      cost: 2,
    },
    BLOOD_WARRIOR: {
      name: "BLOOD_WARRIOR",
      description: [
        "Spawn a health orb after defeating an enemy with a Sneak Attack or Merciless Attack.",
        "Gathering the orbs replenishes 10% of your health.",
      ],
      color: "red",
      cost: 6,
    },
    JUMP_ATTACK_II: {
      name: "JUMP ATTACK II",
      description: [
        "When equipped with a melee weapon, attacking from a double jump deals an additional 20% of weapon damage.",
      ],
      color: "green",
      cost: 3,
    },
    BACKSTAB_MASTERY: {
      name: "BACKSTAB MASTERY",
      description: ["All damage done from the back is increased by 30%."],
      color: "green",
      cost: 4,
    },
    RUNNER: {
      name: "RUNNER",
      description: [
        "Sprinting speed increaased by 10% and stamina consumption decreased by 10%",
      ],
      color: "green",
      cost: 2,
    },
    WANDERLUST: {
      name: "WANDERLUST",
      description: [
        "Stamina consumption for <b>sprinting on dirt roads</b> is reduced from <b>90% to 80%</b>. Stamina consumption for <b>sprinting on stoone roads</b> is reduced from <b>75% to 50%</b>.",
      ],
      color: "green",
      cost: 3,
    },
    GOOD_METABOLISM: {
      name: "GOOD_METABOLISM",
      description: [
        "Health, mana and stamina Orbs restore 30% instead of 10% of their respective resource.",
        "Mana and Health Potions restore 20% more.",
      ],
      color: "green",
      cost: 3,
    },
    SWIFTSHOT_SUSTENANCE: {
      name: "SWIFTSHOT SUSTENANCE",
      description: [
        "30% chance to spawn a stamina orb when defeating an enemy with a bow.",
      ],
      color: "green",
      cost: 2,
    },
    SWEET_TOOTH: {
      name: "SWEET TOOTH",
      description: ["The stamiina regeneration of sweets is increased by 50%"],
      color: "green",
      cost: 3,
    },
    ARACHNOID: {
      name: "ARACHNOID",
      description: ["Stamina consumption while climbing is reduced by 50%"],
      color: "green",
      cost: 3,
    },
    REBOUND: {
      name: "REBOUND",
      description: ["Increase base stamina regeneration by 50%"],
      color: "green",
      cost: 4,
    },
    INNER_FIRES: {
      name: "INNER FIRES",
      description: [
        "Maximum <i>Shroud Time</i> increased by 2 minutes, allowing you to explore for longer.",
        SHROUD_TIME_TEXT,
      ],
      color: "green",
      cost: 2,
    },
    RELENTLESS_FLAME: {
      name: "RELENTLESS_FLAME",
      description: [
        "Maximum <i>Shroud Time</i> increased by 5 minutes, allowing you to explore for longer.",
        SHROUD_TIME_TEXT,
      ],
      color: "green",
      cost: 4,
    },
    SNAKE_EATER: {
      name: "SNAKE_EATER",
      description: [
        "Increases your <b>poison resistance</b> which reduces the damage received from poison by <b>20%</b>.",
      ],
      color: "green",
      cost: 2,
    },
    MITHRIDATIST: {
      name: "MITHRIDATIST",
      description: [
        "Your <b>poison resistance</b> is increased by an additional 10%.",
        "You also gain a 25% chance to avoid being poisoned.",
      ],
      color: "green",
      cost: 3,
    },
    VUKAH_LANGUAGE: {
      name: "VUKAH LANGUAGE",
      description: [
        "Vukah within 50 meters will no longer attack you unless provoked.",
      ],
      color: "green",
      cost: 3,
    },
    CALM_SPIRIT: {
      name: "CALM_SPIRIT",
      description: [
        "<b>Wild animals</b> within 50 meters will be pacified unless attacked. Does not affect animals corrupted by the Shroud.",
      ],
      color: "green",
      cost: 3,
    },
    BEAST_MASTER: {
      name: "BEAST MASTER",
      description: [
        "When you are targeted by an attack, <b>wild animals</b> within 50 meters will attack the enemy.",
      ],
      color: "green",
      cost: 4,
    },
    VUKAH_CULTURE: {
      name: "VUKAH CULTURE",
      description: [
        "When you are targeted by an attack, Vukah within 50 meters will attack the enemy.",
      ],
      color: "green",
      cost: 4,
    },
    ENDURANCE_OF_THE_FLAME: {
      name: "ENDURANCE OF THE FLAME",
      description: [
        "You will gain one endurance for every two levels of the Flame.",
      ],
      color: "green",
      cost: 5,
    },
    MARKSMAN: {
      name: "MARKSMAN",
      description: ["All damage dealt with ranged weapons is increased by 10%"],
      color: "green",
      cost: 2,
    },
    SHARPSHOOTER: {
      name: "SHARPSHOOTER",
      description: ["All ranged damage is increased by an additional 20%"],
      color: "green",
      cost: 2,
    },
    COUNTER_BATTERY: {
      name: "COUNTER BATTERY",
      description: ["+15% damage to ranged enemies."],
      color: "green",
      cost: 2,
    },
    EAGLES_BANE: {
      name: "EAGLES BANE",
      description: ["Damage against flying enemies increased by 30%."],
      color: "green",
      cost: 3,
    },
    SKILL_SHOT: {
      name: "SKILL SHOT",
      description: ["All damage dealt to an enemy's head is increased by 20%."],
      color: "green",
      cost: 3,
    },
    RANGER: {
      name: "RANGER",
      description: [
        "+2 Endurance<br>+2 Dexterity<br>+5 Stamina Recharge<br>+5% Critical Chance<br>+5% Critical Damage",
      ],
      color: "green",
      cost: 5,
    },
    SILENT_STRIDE: {
      name: "SILENT STRIDE",
      description: ["Increases your movement speed while sneaking."],
      color: "green",
      cost: 3,
    },
    AIRBORNE: {
      name: "AIRBORNE",
      description: ["Gliders consume 30% less stamina"],
      color: "green",
      cost: 2,
    },
    SNIPER: {
      name: "SNIPER",
      description: [
        "When attacking with a ranged weapon your critical hit chance is increased by 10%.",
      ],
      color: "green",
      cost: 2,
    },
    VITALITY_SURGE: {
      name: "VITALITY SURGE",
      description: [
        "Dealing a critical strike with a ranged weapon restores 5 stamina.",
      ],
      color: "green",
      cost: 3,
    },
    BLESSED_ARROWS: {
      name: "BLESSED ARROWS",
      description: [
        "When scoring a critical hit with a bow, you will regenerate 20 mana.",
      ],
      color: "green",
      cost: 3,
    },
    BOUNTY_BONANZA: {
      name: "BOUNTY BONANZA",
      description: [
        "After defeating a Fell enemy with a headshot your group gains an additional 5 Experience Points.",
      ],
      color: "green",
      cost: 3,
    },
    RICOCHETS: {
      name: "RICOCHETS",
      description: [
        "For every target you hit with an Exploding Arrow, its damage is increased by 1%.",
      ],
      color: "green",
      cost: 4,
    },
    GRACEFUL_STRIDE: {
      name: "GRACEFUL_STRIDE",
      description: [
        "You will gain one dexterity for every two levels of the Flame.",
      ],
      color: "green",
      cost: 5,
    },
    CHAIN_REACTION: {
      name: "CHAIN REACTION",
      description: [
        "Every enemy hit with an Exploding Arrow has a 20% chance to trigger a secondary explosion for 50% damage in a small radius.",
      ],
      color: "green",
      cost: 5,
    },
    ARCANE_CONCENTRATION: {
      name: "ARCANE_CONCENTRATION",
      description: [
        "You will gain one spirit for every two levels of the Flame.",
      ],
      color: "blue",
      cost: 5,
    },
    EXALTED: {
      name: "EXALTED",
      description: [
        "You will gain oone intelligence for every two levels of the Flame.",
      ],
      color: "blue",
      cost: 5,
    },
    THICK_SKIN: {
      name: "THICK_SKIN",
      description: [
        "You will gain one constitution for each two levels of the Flame.",
      ],
      color: "red",
      cost: 5,
    },
  },
  nodes: {
    "1": {
      id: "1",
      type: "WELL_RESTED",
      base: true,
      tier: "medium",
      distance: -120,
      angle: 255,
    },
    "2": {
      id: "2",
      type: "SNEAK_ATTACK",
      base: true,
      tier: "large",
      distance: -120,
      angle: 225,
    },
    "3": {
      id: "3",
      type: "BACKSTAB_DAMAGE",
      tier: "medium",
      distance: -190,
      angle: 225,
    },
    "4": {
      id: "4",
      type: "LUMBERJACK",
      base: true,
      tier: "medium",
      distance: -120,
      angle: 165,
    },
    "5": {
      id: "5",
      type: "QUALITY_GEAR",
      tier: "medium",
      distance: -120,
      angle: 120,
    },
    "6": { id: "6", type: "MINER", tier: "medium", distance: -190, angle: 120 },
    "7": {
      id: "7",
      type: "MASON",
      base: true,
      tier: "medium",
      distance: -120,
      angle: 75,
    },
    "8": {
      id: "8",
      type: "MERCILESS_ATTACK",
      base: true,
      tier: "large",
      distance: -120,
      angle: 15,
    },
    "9": {
      id: "9",
      type: "POWER_PARRY",
      tier: "medium",
      distance: -190,
      angle: 15,
    },
    "10": {
      id: "10",
      type: "SAVIOUR",
      base: true,
      tier: "medium",
      distance: -120,
      angle: 315,
    },
    "11": {
      id: "11",
      type: "ATTR_SPIRIT",
      base: true,
      tier: "small",
      angle: 255,
    },
    "12": {
      id: "12",
      type: "COUNTERSTRIKE",
      tier: "medium",
      distance: 70,
      angle: 255,
    },
    "13": {
      id: "13",
      type: "ATTR_INT",
      tier: "small",
      distance: 170,
      angle: 250,
    },
    "14": {
      id: "14",
      type: "ATTR_SPIRIT",
      tier: "small",
      distance: 170,
      angle: 260,
    },
    "15": {
      id: "15",
      type: "BEGONE",
      tier: "large",
      distance: 240,
      angle: 255,
    },
    "17": {
      id: "17",
      type: "ATTR_SPIRIT",
      tier: "small",
      distance: 310,
      angle: 250,
    },
    "16": {
      id: "16",
      type: "ATTR_INT",
      tier: "small",
      distance: 310,
      angle: 260,
    },
    "18": {
      id: "18",
      type: "TERROR",
      tier: "medium",
      distance: 380,
      angle: 255,
    },
    "19": {
      id: "19",
      type: "ARCANE_CONCENTRATION",
      tier: "small",
      distance: 450,
      angle: 255,
    },
    "20": {
      id: "20",
      type: "QUICK_CHARGE",
      tier: "medium",
      distance: 120,
      angle: 270,
    },
    "21": { id: "21", type: "ATTR_SPIRIT", base: true, angle: 285 },
    "22": {
      id: "22",
      type: "THIS_IS_THE_WAY",
      tier: "medium",
      distance: 70,
      angle: 285,
    },
    "23": {
      id: "23",
      type: "NECROMANCER",
      tier: "medium",
      distance: 120,
      angle: 300,
    },
    "24": { id: "24", type: "ATTR_SPIRIT", distance: 140, angle: 285 },
    "25": {
      id: "25",
      type: "ARSONIST",
      tier: "medium",
      distance: 210,
      angle: 277,
    },
    "26": {
      id: "26",
      type: "THUNDER",
      tier: "medium",
      distance: 210,
      angle: 285,
    },
    "27": {
      id: "27",
      type: "ICEMAN",
      tier: "medium",
      distance: 210,
      angle: 293,
    },
    "28": {
      id: "28",
      type: "PYROMANIAC",
      tier: "medium",
      distance: 280,
      angle: 277,
    },
    "29": {
      id: "29",
      type: "RADIANT_AURA",
      tier: "large",
      distance: 350,
      angle: 273,
    },
    "30": {
      id: "30",
      type: "SUN_AURA",
      tier: "medium",
      distance: 420,
      angle: 273,
    },
    "31": { id: "31", type: "ATTR_SPIRIT", distance: 490, angle: 273 },
    "32": {
      id: "32",
      type: "LIGHTNING",
      tier: "medium",
      distance: 280,
      angle: 285,
    },
    "33": {
      id: "33",
      type: "SUBZERO",
      tier: "medium",
      distance: 280,
      angle: 293,
    },
    "34": {
      id: "34",
      type: "FROST",
      tier: "medium",
      distance: 350,
      angle: 293,
    },
    "35": { id: "35", type: "ATTR_INT", distance: 350, angle: 285 },
    "36": {
      id: "36",
      type: "WIZARD",
      tier: "medium",
      distance: 420,
      angle: 285,
    },
    "37": {
      id: "37",
      type: "DARK_ARTS",
      tier: "medium",
      distance: 490,
      angle: 282,
    },
    "38": {
      id: "38",
      type: "CHAIN_HIT",
      tier: "medium",
      distance: 490,
      angle: 288,
    },
    "39": {
      id: "39",
      type: "ABYSS",
      tier: "medium",
      distance: 560,
      angle: 282,
    },
    "40": {
      id: "40",
      type: "MASS_DESTRUCTION",
      tier: "medium",
      distance: 560,
      angle: 288,
    },
    "41": { id: "41", type: "ATTR_INT", distance: 630, angle: 285 },
    "42": { id: "42", type: "ATTR_INT", base: true, angle: 315 },
    "43": {
      id: "43",
      type: "HEALER",
      tier: "medium",
      distance: 70,
      angle: 315,
    },
    "44": {
      id: "44",
      type: "HEALER_II",
      tier: "medium",
      distance: 140,
      angle: 315,
    },
    "45": { id: "45", type: "ATTR_INT", distance: 210, angle: 315 },
    "46": {
      id: "46",
      type: "WATER_AURA",
      tier: "large",
      distance: 280,
      angle: 320,
    },
    "47": {
      id: "47",
      type: "HEALING_REVIVE",
      tier: "medium",
      distance: 280,
      angle: 310,
    },
    "48": {
      id: "48",
      type: "SHROUD_FILTER",
      tier: "medium",
      distance: 340,
      angle: 315,
    },
    "49": {
      id: "49",
      type: "WATERS_OF_LIFE",
      tier: "medium",
      distance: 330,
      angle: 325,
    },
    "50": { id: "50", type: "ATTR_SPIRIT", distance: 340, angle: 306 },
    "51": { id: "51", type: "ATTR_INT", distance: 410, angle: 312 },
    "52": { id: "52", type: "ATTR_SPIRIT", distance: 410, angle: 318 },
    "53": {
      id: "53",
      type: "MARTYR",
      tier: "large",
      distance: 480,
      angle: 315,
    },
    "54": { id: "54", type: "EXALTED", distance: 550, angle: 315 },
    "55": { id: "55", type: "BLINK", tier: "large", distance: 120, angle: 330 },
    "56": {
      id: "56",
      type: "EMERGENCY_BLINK",
      tier: "medium",
      distance: 180,
      angle: 327,
    },
    "57": {
      id: "57",
      type: "BLINK_ATTACK",
      tier: "medium",
      distance: 180,
      angle: 333,
    },
    "58": { id: "58", type: "ATTR_INT", base: true, angle: 345 },
    "59": {
      id: "59",
      type: "ARCANE_DEFLECTION",
      tier: "medium",
      distance: 70,
      angle: 345,
    },
    "60": {
      id: "60",
      type: "EVASION_ATTACK",
      tier: "large",
      distance: 120,
      angle: 360,
    },
    "61": {
      id: "61",
      type: "BATTLE_HEAL",
      tier: "medium",
      distance: 190,
      angle: 360,
    },
    "62": { id: "62", type: "ATTR_SPIRIT", distance: 260, angle: 360 },
    "63": { id: "63", type: "ABSORB", tier: "medium", distance: 320, angle: 3 },
    "64": {
      id: "64",
      type: "BLOODLETTING",
      tier: "medium",
      distance: 320,
      angle: 357,
    },
    "65": { id: "65", type: "SNAP", tier: "medium", distance: 390, angle: 3 },
    "66": {
      id: "66",
      type: "LIFE_BURST",
      tier: "medium",
      distance: 390,
      angle: 357,
    },
    "67": {
      id: "67",
      type: "SOUL_LEECH",
      tier: "medium",
      distance: 460,
      angle: 3,
    },
    "68": {
      id: "68",
      type: "BLOOD_MAGIC",
      tier: "medium",
      distance: 460,
      angle: 357,
    },
    "69": { id: "69", type: "ATTR_INT", distance: 140, angle: 345 },
    "70": { id: "70", type: "UNITY", tier: "large", distance: 210, angle: 345 },
    "72": {
      id: "72",
      type: "STING",
      tier: "medium",
      distance: 270,
      angle: 340,
    },
    "71": {
      id: "71",
      type: "WAND_MASTER",
      tier: "medium",
      distance: 270,
      angle: 350,
    },
    "73": { id: "73", type: "ATTR_SPIRIT", distance: 350, angle: 345 },
    "74": { id: "74", type: "ATTR_INT", distance: 420, angle: 345 },
    "75": { id: "75", type: "ATTR_CONS", base: true, angle: 15 },
    "76": {
      id: "76",
      type: "SHINY_PLATES",
      tier: "medium",
      distance: 70,
      angle: 15,
    },
    "77": {
      id: "77",
      type: "HEAVY_PLATES",
      tier: "medium",
      distance: 140,
      angle: 15,
    },
    "78": {
      id: "78",
      type: "ATTR_CONS",
      tier: "medium",
      distance: 210,
      angle: 15,
    },
    "79": { id: "79", type: "TOWER", tier: "medium", distance: 280, angle: 20 },
    "80": {
      id: "80",
      type: "WARDEN",
      tier: "medium",
      distance: 280,
      angle: 10,
    },
    "81": { id: "81", type: "ATTR_STR", distance: 350, angle: 25 },
    "82": { id: "82", type: "ATTR_STR", distance: 350, angle: 18 },
    "83": { id: "83", type: "ATTR_CONS", distance: 350, angle: 12 },
    "84": {
      id: "84",
      type: "NEMESIS",
      tier: "large",
      distance: 420,
      angle: 25,
    },
    "85": {
      id: "85",
      type: "ARCH_NEMESIS",
      tier: "medium",
      distance: 490,
      angle: 25,
    },
    "86": {
      id: "86",
      type: "EARTH_AURA",
      tier: "large",
      distance: 480,
      angle: 15,
    },
    "87": { id: "87", type: "THICK_SKIN", distance: 550, angle: 15 },
    "88": { id: "88", type: "ATTR_CONS", base: true, angle: 45 },
    "89": {
      id: "89",
      type: "WARRIOR_PATH",
      tier: "medium",
      distance: 70,
      angle: 45,
    },
    "90": {
      id: "90",
      type: "PURIFICATION",
      tier: "medium",
      distance: 120,
      angle: 30,
    },
    "91": { id: "91", type: "ATTR_STR", distance: 140, angle: 45 },
    "92": {
      id: "92",
      type: "SLASHER",
      tier: "medium",
      distance: 210,
      angle: 55,
    },
    "93": { id: "93", type: "BRUTE", tier: "medium", distance: 210, angle: 45 },
    "94": {
      id: "94",
      type: "THRUST",
      tier: "medium",
      distance: 210,
      angle: 35,
    },
    "95": {
      id: "95",
      type: "BUTCHER",
      tier: "medium",
      distance: 280,
      angle: 55,
    },
    "96": {
      id: "96",
      type: "HAMMER_TIME",
      tier: "medium",
      distance: 280,
      angle: 45,
    },
    "97": {
      id: "97",
      type: "PIERCE",
      tier: "medium",
      distance: 280,
      angle: 35,
    },
    "98": {
      id: "98",
      type: "VETERAN",
      tier: "medium",
      distance: 350,
      angle: 45,
    },
    "99": { id: "99", type: "ATTR_CONS", distance: 420, angle: 50 },
    "100": { id: "100", type: "ATTR_STR", distance: 420, angle: 40 },
    "101": {
      id: "101",
      type: "SWIFT_BLADES",
      tier: "large",
      distance: 490,
      angle: 45,
    },
    "102": { id: "102", type: "ATTR_CONS", distance: 560, angle: 45 },
    "103": { id: "103", type: "ATTR_STR", base: true, angle: 75 },
    "104": {
      id: "104",
      type: "HEAVY_HANDED",
      tier: "medium",
      distance: 70,
      angle: 75,
    },
    "105": { id: "105", type: "ATTR_STR", distance: 140, angle: 75 },
    "106": {
      id: "106",
      type: "FEAST",
      tier: "medium",
      distance: 120,
      angle: 60,
    },
    "107": { id: "107", type: "ATTR_CONS", distance: 210, angle: 75 },
    "108": {
      id: "108",
      type: "RELENTLESS",
      tier: "medium",
      distance: 280,
      angle: 80,
    },
    "109": {
      id: "109",
      type: "BREACH",
      tier: "medium",
      distance: 280,
      angle: 70,
    },
    "110": {
      id: "110",
      type: "SHOCKWAVE",
      tier: "large",
      distance: 350,
      angle: 60,
    },
    "111": { id: "111", type: "ATTR_CONS", distance: 380, angle: 75 },
    "112": {
      id: "112",
      type: "HEAVY_SPECIALIZATION",
      tier: "large",
      distance: 450,
      angle: 75,
    },
    "113": { id: "113", type: "BARBARIAN", distance: 520, angle: 75 },
    "114": {
      id: "114",
      type: "BLOOD_RAGE",
      tier: "medium",
      distance: 590,
      angle: 75,
    },
    "115": { id: "115", type: "ATTR_STR", base: true, angle: 105 },
    "116": {
      id: "116",
      type: "JUMP_ATTACK",
      tier: "large",
      distance: 70,
      angle: 105,
    },
    "117": {
      id: "117",
      type: "DOUBLE_JUMP",
      tier: "large",
      distance: 120,
      angle: 120,
    },
    "118": {
      id: "118",
      type: "JUMP_ATTACK_II",
      tier: "medium",
      distance: 190,
      angle: 120,
    },
    "119": { id: "119", type: "ATTR_STR", distance: 190, angle: 105 },
    "120": {
      id: "120",
      type: "BLOOD_WARRIOR",
      tier: "medium",
      distance: 260,
      angle: 110,
    },
    "178": {
      id: "178",
      type: "BACKSTAB_MASTERY",
      tier: "medium",
      distance: 310,
      angle: 120,
    },
    "121": {
      id: "121",
      type: "VIGOROUS_DEFLECTION",
      tier: "medium",
      distance: 260,
      angle: 100,
    },
    "122": { id: "122", type: "ATTR_CONS", distance: 330, angle: 105 },
    "123": { id: "123", type: "ATTR_CONS", distance: 400, angle: 110 },
    "124": { id: "124", type: "ATTR_STR", distance: 400, angle: 100 },
    "125": { id: "125", type: "BASH", tier: "large", distance: 310, angle: 90 },
    "126": { id: "126", type: "ATTR_STR", distance: 380, angle: 90 },
    "127": { id: "127", type: "ATTR_ENDURANCE", base: true, angle: 135 },
    "128": {
      id: "128",
      type: "RUNNER",
      tier: "medium",
      distance: 70,
      angle: 135,
    },
    "129": {
      id: "129",
      type: "INNER_FIRES",
      tier: "medium",
      distance: 120,
      angle: 150,
    },
    "130": { id: "130", type: "ATTR_ENDURANCE", distance: 140, angle: 135 },
    "131": {
      id: "131",
      type: "WANDERLUST",
      tier: "medium",
      distance: 210,
      angle: 135,
    },
    "132": {
      id: "132",
      type: "GOOD_METABOLISM",
      tier: "medium",
      distance: 280,
      angle: 140,
    },
    "133": {
      id: "133",
      type: "SWIFTSHOT_SUSTENANCE",
      tier: "medium",
      distance: 280,
      angle: 130,
    },
    "134": { id: "134", type: "REBOUND", distance: 320, angle: 135 },
    "135": {
      id: "135",
      type: "SWEET_TOOTH",
      tier: "medium",
      distance: 370,
      angle: 140,
    },
    "136": {
      id: "136",
      type: "ARACHNOID",
      tier: "medium",
      distance: 370,
      angle: 130,
    },
    "137": { id: "137", type: "ATTR_DEX", distance: 440, angle: 135 },
    "138": {
      id: "138",
      type: "DESSERT_STOMACH",
      tier: "large",
      distance: 510,
      angle: 135,
    },
    "139": { id: "139", type: "ATTR_ENDURANCE", distance: 580, angle: 135 },
    "140": { id: "140", type: "ATTR_ENDURANCE", base: true, angle: 165 },
    "141": {
      id: "141",
      type: "SNAKE_EATER",
      tier: "medium",
      distance: 70,
      angle: 165,
    },
    "142": {
      id: "142",
      type: "EAGLE_EYE",
      tier: "large",
      distance: 120,
      angle: 180,
    },
    "143": {
      id: "143",
      type: "MITHRIDATIST",
      tier: "medium",
      distance: 140,
      angle: 165,
    },
    "144": { id: "144", type: "ATTR_ENDURANCE", distance: 210, angle: 165 },
    "145": {
      id: "145",
      type: "VUKAH_LANGUAGE",
      tier: "medium",
      distance: 280,
      angle: 170,
    },
    "146": {
      id: "146",
      type: "CALM_SPIRIT",
      tier: "medium",
      distance: 280,
      angle: 160,
    },
    "179": {
      id: "179",
      type: "RELENTLESS_FLAME",
      tier: "medium",
      distance: 330,
      angle: 150,
    },
    "147": { id: "147", type: "ATTR_DEX", distance: 310, angle: 165 },
    "148": { id: "148", type: "ATTR_ENDURANCE", distance: 310, angle: 175 },
    "149": {
      id: "149",
      type: "VUKAH_CULTURE",
      tier: "medium",
      distance: 370,
      angle: 170,
    },
    "150": {
      id: "150",
      type: "BEAST_MASTER",
      tier: "medium",
      distance: 370,
      angle: 160,
    },
    "151": { id: "151", type: "ATTR_DEX", distance: 400, angle: 175 },
    "152": {
      id: "152",
      type: "ENDURANCE_OF_THE_FLAME",
      distance: 440,
      angle: 165,
    },
    "153": { id: "153", type: "ATTR_DEX", base: true, angle: 195 },
    "154": {
      id: "154",
      type: "MARKSMAN",
      tier: "medium",
      distance: 70,
      angle: 195,
    },
    "155": {
      id: "155",
      type: "SILENT_STRIDE",
      tier: "medium",
      distance: 120,
      angle: 210,
    },
    "156": {
      id: "156",
      type: "SHARPSHOOTER",
      tier: "medium",
      distance: 200,
      angle: 200,
    },
    "157": {
      id: "157",
      type: "COUNTER_BATTERY",
      tier: "medium",
      distance: 200,
      angle: 190,
    },
    "158": {
      id: "158",
      type: "EAGLES_BANE",
      tier: "medium",
      distance: 320,
      angle: 200,
    },
    "159": {
      id: "159",
      type: "SKILL_SHOT",
      tier: "medium",
      distance: 320,
      angle: 190,
    },
    "160": {
      id: "160",
      type: "BEE_STING",
      tier: "large",
      distance: 400,
      angle: 205,
    },
    "161": {
      id: "161",
      type: "RANGER",
      tier: "medium",
      distance: 420,
      angle: 195,
    },
    "162": {
      id: "162",
      type: "MULTI_SHOT",
      tier: "large",
      distance: 400,
      angle: 185,
    },
    "163": { id: "163", type: "ATTR_DEX", base: true, angle: 225 },
    "164": {
      id: "164",
      type: "AIRBORNE",
      tier: "medium",
      distance: 70,
      angle: 225,
    },
    "165": {
      id: "165",
      type: "UPDRAFT",
      tier: "large",
      distance: 120,
      angle: 240,
    },
    "166": { id: "166", type: "ATTR_ENDURANCE", distance: 140, angle: 225 },
    "167": {
      id: "167",
      type: "SNIPER",
      tier: "medium",
      distance: 210,
      angle: 225,
    },
    "168": {
      id: "168",
      type: "VITALITY_SURGE",
      tier: "medium",
      distance: 280,
      angle: 230,
    },
    "169": {
      id: "169",
      type: "BLESSED_ARROWS",
      tier: "medium",
      distance: 280,
      angle: 220,
    },
    "170": { id: "170", type: "ATTR_DEX", distance: 350, angle: 235 },
    "171": {
      id: "171",
      type: "SHELL_SHOCK",
      tier: "large",
      distance: 420,
      angle: 235,
    },
    "172": {
      id: "172",
      type: "BOUNTY_BONANZA",
      tier: "medium",
      distance: 350,
      angle: 225,
    },
    "173": { id: "173", type: "ATTR_DEX", distance: 350, angle: 215 },
    "174": {
      id: "174",
      type: "RICOCHETS",
      tier: "medium",
      distance: 420,
      angle: 225,
    },
    "175": { id: "175", type: "GRACEFUL_STRIDE", distance: 490, angle: 225 },
    "176": { id: "176", type: "ATTR_ENDURANCE", distance: 490, angle: 220 },
    "177": {
      id: "177",
      type: "CHAIN_REACTION",
      tier: "medium",
      distance: 560,
      angle: 225,
    },
  },
  edges: {
    "1": [],
    "2": ["3"],
    "3": ["2"],
    "4": ["5", "6"],
    "5": ["4", "7"],
    "6": ["4", "7"],
    "7": ["5", "6"],
    "8": ["9"],
    "9": ["8"],
    "10": [],
    "11": ["12"],
    "12": ["11", "13", "14", "20", "165"],
    "13": ["12", "15"],
    "14": ["12", "15"],
    "15": ["13", "14", "16", "17"],
    "16": ["15", "18"],
    "17": ["15", "18"],
    "18": ["16", "17", "19"],
    "19": ["18"],
    "20": ["12", "22"],
    "21": ["22"],
    "22": ["20", "24", "23"],
    "23": ["22", "43"],
    "24": ["22", "25", "26", "27"],
    "25": ["24", "28"],
    "26": ["24", "32"],
    "27": ["24", "33"],
    "28": ["25", "29", "35"],
    "29": ["28", "30"],
    "30": ["29", "31"],
    "31": ["30"],
    "32": ["26", "35"],
    "33": ["27", "35", "34"],
    "34": ["33"],
    "35": ["28", "32", "33", "36"],
    "36": ["35", "37", "38"],
    "37": ["36", "39"],
    "38": ["36", "40"],
    "39": ["37"],
    "40": ["38", "41"],
    "41": ["40"],
    "42": ["43"],
    "43": ["42", "23", "44", "55"],
    "44": ["43", "45"],
    "45": ["44", "47", "48", "46"],
    "46": ["45", "49", "52"],
    "47": ["45", "50", "51"],
    "48": ["45"],
    "49": ["46"],
    "50": ["47"],
    "51": ["47", "53"],
    "52": ["46", "53"],
    "53": ["51", "52", "54"],
    "54": ["53"],
    "55": ["43", "56", "57", "59"],
    "56": ["55"],
    "57": ["55"],
    "58": ["59"],
    "59": ["58", "55", "69", "60"],
    "60": ["59", "76", "61"],
    "61": ["60", "62"],
    "62": ["61", "63", "64"],
    "63": ["62", "65"],
    "64": ["62", "66"],
    "65": ["63", "67"],
    "66": ["64", "68"],
    "67": ["65"],
    "68": ["66"],
    "69": ["59", "70"],
    "70": ["69", "72", "73", "71"],
    "71": ["70"],
    "72": ["70"],
    "73": ["70", "74"],
    "74": ["73"],
    "75": ["76"],
    "76": ["75", "60", "77", "90"],
    "77": ["76", "78"],
    "78": ["77", "80", "79"],
    "79": ["78", "81", "82"],
    "80": ["78", "83"],
    "81": ["79", "84"],
    "82": ["79", "86"],
    "83": ["80", "86"],
    "84": ["81", "85"],
    "85": ["84"],
    "86": ["82", "83", "87"],
    "87": ["86"],
    "88": ["89"],
    "89": ["88", "90", "91", "106"],
    "90": ["89", "76"],
    "91": ["89", "92", "93", "94"],
    "92": ["91", "95"],
    "93": ["91", "96"],
    "94": ["91", "97"],
    "95": ["92", "98"],
    "96": ["93", "98"],
    "97": ["94", "98"],
    "98": ["95", "96", "97", "99", "101", "100"],
    "99": ["98"],
    "100": ["98"],
    "101": ["98", "102"],
    "102": ["101"],
    "103": ["104"],
    "104": ["103", "106", "105"],
    "105": ["104", "107"],
    "106": ["104", "89"],
    "107": ["105", "108", "109"],
    "108": ["107", "111", "125"],
    "109": ["107", "111", "110"],
    "110": ["109"],
    "111": ["108", "109", "112"],
    "112": ["111", "113"],
    "113": ["112", "114"],
    "114": ["113"],
    "115": ["116"],
    "116": ["115", "117", "119"],
    "117": ["116", "118", "128"],
    "118": ["117"],
    "119": ["116", "120", "121"],
    "120": ["119", "178", "122"],
    "121": ["119", "122", "125"],
    "122": ["120", "121", "123", "124"],
    "123": ["122"],
    "124": ["122"],
    "125": ["121", "108", "126"],
    "126": ["125"],
    "127": ["128"],
    "128": ["127", "117", "130", "129"],
    "129": ["128", "141"],
    "130": ["128", "131"],
    "131": ["130", "132", "133"],
    "132": ["131", "179", "135", "134"],
    "133": ["131", "136", "178"],
    "134": ["132"],
    "135": ["132", "137"],
    "136": ["133", "137"],
    "137": ["135", "136", "138"],
    "138": ["137", "139"],
    "139": ["138"],
    "140": ["141"],
    "141": ["140", "129", "143", "142"],
    "142": ["141", "154"],
    "143": ["141", "144"],
    "144": ["143", "145", "146"],
    "145": ["144", "148", "149", "147"],
    "146": ["144", "147", "150", "179"],
    "147": ["145", "146"],
    "148": ["145"],
    "149": ["145", "151", "152"],
    "150": ["146", "152"],
    "151": ["149"],
    "152": ["149", "150"],
    "153": ["154"],
    "154": ["153", "142", "155", "156", "157"],
    "155": ["154", "164"],
    "156": ["154", "159"],
    "157": ["154", "158"],
    "158": ["157", "160", "161"],
    "159": ["156", "161", "162"],
    "160": ["158"],
    "161": ["158", "159"],
    "162": ["159"],
    "163": ["164"],
    "164": ["163", "165", "166", "155"],
    "165": ["164", "12"],
    "166": ["164", "167"],
    "167": ["166", "168", "169"],
    "168": ["167", "170", "172"],
    "169": ["167", "172", "173"],
    "170": ["168", "171"],
    "171": ["170"],
    "172": ["168", "169", "174"],
    "173": ["169"],
    "174": ["175", "176"],
    "175": ["174", "177"],
    "176": ["174"],
    "177": ["175"],
    "178": ["120", "133"],
    "179": ["132", "146"],
  },
};

export default SkillNodes;
